### ISSUE TITLE
C# Antlr4.Runtime.Standard v4.7.2.0 assembly signature problem

### ISSUE THREAD

**Issue by jimmy-the-eek** [antlr/antlr4#2700] opened 2019-12-12 12:14 UTC
The assembly works for code generation, but I have to downgrade to 4.7.1.1 to get the console runner to work. Error message follows.

```
Unit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.6.1, runtime: 4.0.30319.42000)
System.IO.FileLoadException: Could not load file or assembly 'Antlr4.Runtime.Standard, Version=4.7.2.0, Culture=neutral, PublicKeyToken=e78b2c5abd1fcb3f' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

```

**Comment by ericvergnaud** [comment] 2019-12-15 09:40
@parrt we need this one fixed in the upcoming release
@jimmy-the-eek can you help provide a fix?

**Comment by Silvenga** [comment] 2019-12-15 20:31
@ericvergnaud isn't this the same as https://github.com/antlr/antlr4/issues/2511? The strong name is failing validation due to the "open" signature.

**Comment by ericvergnaud** [comment] 2019-12-16 04:36
Most probably yes


Envoyé de mon iPhone

**Comment by parrt** [comment] 2019-12-16 16:43
Shall I call this a dup and close?

**Comment by sharwell** [comment] 2019-12-16 16:58
@parrt Yes it's the same issue

**Closed** 2019-12-16 18:42 UTC
Labels: comp:tool, status:duplicate, target:csharp

**Comment by sharwell** [comment] 2019-12-16 22:41
Duplicate of #2511
