### ISSUE TITLE
fetchedEOF field holds true even after call on reset() in BufferedTokenStream

### ISSUE THREAD

**Issue by pablo53** [antlr/antlr4#962] opened 2015-07-27 22:57 UTC
BufferedTokenStream.reset() leaves boolean field fetchedEOF intact, making it impossible to reuse the stream object after the first EOF is hit.

**Comment by sharwell** [comment] 2015-07-28 00:53
This is a duplicate of #895, where we decided not to make a change to this method. If you are running into problems with a particular use pattern, can you post an example as a comment in that method? I'm interested to see how this is affecting you and if there's anything we can do to improve it.

**Closed** 2016-12-10 23:00 UTC
Labels: status:duplicate
