### ISSUE TITLE
Antlr4 Not following alternate path when second predicate fails

### ISSUE THREAD

**Issue by singhshiva88** [antlr/antlr4#1567] opened 2016-12-30 07:57 UTC
@parser::members {

public boolean twoDigitDay(String text) {
    try {
        int day = Integer.parseInt(text);
        if (day >= 1 && day <= 31)
        {
            return true;
        }
    }
    catch (Exception e)
    {

    }
    return false;
}
public boolean twoDigitMonth(String text) {
    try {
        int day = Integer.parseInt(text);
        if (day >= 1 && day <= 12)
        {
            return true;
        }
    }
    catch (Exception e)
    {
    }
    return false;
}
}

date        :   day seperator month
        |   month seperator day
        ;

day             :   dayTwoDigits ;
month           :   monthTwoDigit;
monthTwoDigit   :   {twoDigitMonth(getCurrentToken().getText())}? TWO_DIGITS;
dayTwoDigits    :   {twoDigitDay(getCurrentToken().getText())}? TWO_DIGITS;
seperator   :   ('/');
ONE_DIGIT   :   [0-9];
TWO_DIGIT   :   ONE_DIGIT ONE_DIGIT

Problem here is: input - 12/29 (it should go to month seperator day path because first is failing). Parser is throwing No Viable Input at 29... Since 29 doesn't satisfy the month criteria which is define in @member . In this case 12 is passed according to date method (1-31) after that 29 is going to month check(1-12) and it fails. It should backtrack to the root and follow the second path rather than giving No Viable Input at 29 exception.

**Comment by mike-lischke** [comment] 2016-12-30 14:48
I believe this can be closed as it is not a bug of antlr4ts.

**Comment by sharwell** [comment] 2017-01-02 15:45
Semantic predicates are only evaluated on the left edge of a decision in ANTLR 4 parser rules. In the example grammar, the `date` rule has the only decision:

```antlr
date
  : day seperator month
  | month seperator day
  ;
```

Notice that in this rule, `day` and `month` each appear twice. However, only the predicates visible from a decision will be used for prediction. For the sake of making a decision, the rule is equivalent to the following:

```
date
  : day seperator TWO_DIGITS
  | month seperator TWO_DIGITS
  ;
```

If you want to have ANTLR parse a rule like the `date` rule written above, you'll need to rewrite it without using semantic predicates or you'll end up seeing exceptions for some inputs.

**Closed** 2017-01-05 22:54 UTC
