### ISSUE TITLE
Context sensitive parsing bug

### ISSUE THREAD

**Issue by aijmartin** [antlr/antlr4#1097] opened 2016-01-25 16:07 UTC
Hi,

I've come across a bug whilst trying trying to track down why the parser I'm working on is resorting to context sensitive parsing.  The bug is reproducible using the simple grammar below with the following sample input:

SELECT a.x, b.y

In the grammar below, the from_table_source_clause rule is not actually used (it should ultimately be part of the query_specification rule) but different outputs are obtained depending on whether or not this rule is included in the grammar source file.

Compiling and running the grammar as is produces the following output:

$ antlr4 qtn.g4
$ javac *.java
$ grun qtn query_specification -diagnostics < test.sql
Warning: TestRig moved to org.antlr.v4.gui.TestRig; calling automatically
line 2:0 reportAttemptingFullContext d=3 (qualified_table_name), input='a.x,b.y'
line 1:10 reportContextSensitivity d=3 (qualified_table_name), input='a.x,'
line 2:0 reportAttemptingFullContext d=3 (qualified_table_name), input='b.y'
line 2:0 reportContextSensitivity d=3 (qualified_table_name), input='b.y'
$

If the grammar is now modified by removing the following lines...

from_table_source_clause :
    'FROM' qualified_table_name ( ',' qualified_table_name )*
;

...the output now changes to the following:

$ rm *.class
$ antlr4 qtn.g4
$ javac *.java
$ grun qtn query_specification -diagnostics < test.sql
Warning: TestRig moved to org.antlr.v4.gui.TestRig; calling automatically
$

It would appear that the parser is now able to parse the test file without using context sensitive parsing even though the only change was to remove a grammar rule which was never used in the first place.  Since the from_table_source_clause rule was never used in the original grammar, its removal should have no material impact on the parser and its output.

Jonathan

grammar qtn;

query_specification :
    'SELECT' select_item_comma_seq
;

select_item_comma_seq :
    qualified_column_name ( ',' qualified_column_name )*
;

from_table_source_clause :
    'FROM' qualified_table_name ( ',' qualified_table_name )*
;

qualified_column_name :
    ( qualified_table_name '.' )? column_name
;

qualified_table_name :
    ( schema_name '.' )? table_name
;

schema_name   : IDENTIFIER ;
table_name    : IDENTIFIER ;
column_name   : IDENTIFIER ;

IDENTIFIER :
    [a-zA-Z_][a-zA-Z_0-9@$#]*
;

WHITE_SPACE :
    [ \t\r\n]+ -> skip
;

**Comment by sharwell** [comment] 2016-01-26 00:43
Duplicate of #985, and caused by #118.

To fix it, you need to update your start rule to have an explicit EOF.

```antlr
query_specification :
 'SELECT' select_item_comma_seq EOF
 ;
```

**Comment by aijmartin** [comment] 2016-01-26 09:49
Thanks Sam.  I tried your suggestion but got exactly the same behaviour as before so maybe this is a different issue?

Jonathan

**Comment by sharwell** [comment] 2016-01-26 15:19
Hi @aijmartin,

It seems I misinterpreted your original question. In both cases the parse result was correct, but in only one case it had to use LL prediction.

ANTLR 4 uses LL prediction any time it can't be *absolutely certain* that the SLL prediction is correct. This occurs in practice for many grammars, including unambiguous grammars. To avoid the performance overhead associated with LL prediction for real-world scenarios, we spent quite a bit of time proving that the two-stage parsing strategy always produces correct results. This involves first parsing an input in SLL-only mode, and then only using LL mode if an error is reported.

**Closed** 2016-01-28 19:16 UTC
Labels: status:invalid

**Comment by aijmartin** [comment] 2016-01-29 10:56
Hi Sam,

That's interesting.  So, I was able to verify what you said by tracing the parse using the SLL option (outputs below) and can see now why you wouldn't consider this to be a bug.

What's interesting to me though is that the SLL parse is actually different in the two cases.

In the first case (where the from_table_source_clause rule is part of the grammar), the SLL parse incorrectly identifies a.x as <schema_name><dot><table_name> and then fails because there is no <dot><column_name> that follows.

When the from_table_source_clause rule is removed from the grammar, the SLL parse is able to correctly identify that a.x is actually <table_name><dot><column_name> and the parse succeeds.

Why is it different in each case?  I appreciate the difficulty in parsing the qualified construct - it's impossible to tell exactly what each dot-separated element of the qualified table name should be until all of the elements have been encountered.  However, I'd still expect the result to be the same in both cases (either both correct or both incorrect).

Why is that a rule that is unreachable for a particular parse can influence the result of the parse through its presence or absence?

Just trying to further my understanding at this point...

Jonathan

$ grun qtn query_specification -trace -diagnostics -SLL < test.sql
Warning: TestRig moved to org.antlr.v4.gui.TestRig; calling automatically
enter   query_specification, LT(1)=SELECT
consume [@0,0:5='SELECT',<1>,1:0] rule query_specification
enter   select_item_comma_seq, LT(1)=a
enter   qualified_column_name, LT(1)=a
enter   qualified_table_name, LT(1)=a
enter   schema_name, LT(1)=a
**consume [@1,7:7='a',<5>,1:7] rule schema_name**
exit    schema_name, LT(1)=.
consume [@2,8:8='.',<4>,1:8] rule qualified_table_name
enter   table_name, LT(1)=x
**consume [@3,9:9='x',<5>,1:9] rule table_name**
exit    table_name, LT(1)=,
exit    qualified_table_name, LT(1)=,
**line 1:10 mismatched input ',' expecting '.'**
exit    qualified_column_name, LT(1)=,
consume [@4,10:10=',',<2>,1:10] rule select_item_comma_seq
enter   qualified_column_name, LT(1)=b
enter   qualified_table_name, LT(1)=b
enter   schema_name, LT(1)=b
consume [@5,12:12='b',<5>,1:12] rule schema_name
exit    schema_name, LT(1)=.
consume [@6,13:13='.',<4>,1:13] rule qualified_table_name
enter   table_name, LT(1)=y
consume [@7,14:14='y',<5>,1:14] rule table_name
exit    table_name, LT(1)=<EOF>
exit    qualified_table_name, LT(1)=<EOF>
line 2:0 mismatched input '<EOF>' expecting '.'
exit    qualified_column_name, LT(1)=<EOF>
exit    select_item_comma_seq, LT(1)=<EOF>
consume [@8,17:16='<EOF>',<-1>,2:0] rule query_specification
exit    query_specification, LT(1)=<EOF>
$

$ grun qtn query_specification -trace -diagnostics -SLL < test.sql
Warning: TestRig moved to org.antlr.v4.gui.TestRig; calling automatically
enter   query_specification, LT(1)=SELECT
consume [@0,0:5='SELECT',<1>,1:0] rule query_specification
enter   select_item_comma_seq, LT(1)=a
enter   qualified_column_name, LT(1)=a
enter   qualified_table_name, LT(1)=a
enter   table_name, LT(1)=a
**consume [@1,7:7='a',<4>,1:7] rule table_name**
exit    table_name, LT(1)=.
exit    qualified_table_name, LT(1)=.
consume [@2,8:8='.',<3>,1:8] rule qualified_column_name
enter   column_name, LT(1)=x
**consume [@3,9:9='x',<4>,1:9] rule column_name**
exit    column_name, LT(1)=,
exit    qualified_column_name, LT(1)=,
consume [@4,10:10=',',<2>,1:10] rule select_item_comma_seq
enter   qualified_column_name, LT(1)=b
enter   qualified_table_name, LT(1)=b
enter   table_name, LT(1)=b
consume [@5,12:12='b',<4>,1:12] rule table_name
exit    table_name, LT(1)=.
exit    qualified_table_name, LT(1)=.
consume [@6,13:13='.',<3>,1:13] rule qualified_column_name
enter   column_name, LT(1)=y
consume [@7,14:14='y',<4>,1:14] rule column_name
exit    column_name, LT(1)=<EOF>
exit    qualified_column_name, LT(1)=<EOF>
exit    select_item_comma_seq, LT(1)=<EOF>
consume [@8,17:16='<EOF>',<-1>,2:0] rule query_specification
exit    query_specification, LT(1)=<EOF>

**Comment by sharwell** [comment] 2016-01-29 12:55
It's important to note that `from_table_source_clause` is not unreachable:

> grun qtn from_table_source_clause -trace -diagnostics -SLL &lt; test.sql

However, as you noticed `from_table_source_clause` is unreachable when you start parsing at `query_specification`. The difference between SLL and LL parsing is the prediction algorithm doesn't know where you started for SLL, but it does know where you started for LL parsing.

**Comment by aijmartin** [comment] 2016-02-03 16:53
Hi Sam,

Many thanks for the additional info.  Think I would need to do some further reading around the SLL and LL algorithms to understand the detail of this but I certainly have a much better idea of what's happening now than I did originally.

Thanks,

Jonathan
