### ISSUE TITLE
Uncaught SyntaxError: Identifier '_alt' has already been declared

### ISSUE THREAD

**Issue by yulingtianxia** [antlr/antlr4#2980] opened 2020-11-29 17:29 UTC
This issue happends on JS runtime target with antlr 4.9, for example:

``` bash
antlr4 -Dlanguage=JavaScript Java9.g4
```

The generated file `Java9Parser.js` run with this error.

**Comment by ericvergnaud** [comment] 2020-11-30 12:30
Hi,
does not happen with all grammars.
Can you produce the smallest grammar that triggers the issue?

**Comment by yulingtianxia** [comment] 2020-11-30 13:50
> Hi,
> does not happen with all grammars.
> Can you produce the smallest grammar that triggers the issue?

Hello, I can produce this issue by [`Java9.g4`](https://github.com/antlr/grammars-v4/blob/master/java/java9/Java9.g4).

**Comment by ericvergnaud** [comment] 2020-12-02 16:15
That's not a small grammar.

**Comment by XStepien** [comment] 2020-12-03 16:17
Hello, i can reproduce this issue with a "medium sized" grammar when trying to update from Antlr 4.8 to 4.9 (Javascript Runtime).

Also, it would be great if the documentation could give a concrete example of migration from 4.8 to 4.9 Javascript parser (visitor/listener).

**Comment by ericvergnaud** [comment] 2020-12-03 16:24
@XStepien re docs feel free to submit a PR
re the issue, I'm looking for a 10 rules grammar where the issue can be reproduced.

**Comment by ericvergnaud** [comment] 2020-12-03 16:27
could relate to a * and + in the same rule

**Comment by ericvergnaud** [comment] 2020-12-03 16:33
alternately please post here the generated code fragment where this happens and the corresponding grammar fragment

**Comment by XStepien** [comment] 2020-12-03 16:34
I have this kind of rule:
```
expr : expr WS? Calc_ope WS? expr
    | Parenthesis WS? expr WS? ParenthesisEnd
    | operand
    ;
```

Where "Calc_ope" is : 
```
Calc_ope: Mult | Div | Add | Sub;

Mult: '*';
Div: '/';
Add: '+';
Sub: '-';
```

Hope this help

**Comment by ericvergnaud** [comment] 2020-12-03 16:36
and that rule generates invalid javascript?

**Comment by XStepien** [comment] 2020-12-03 16:40
I don't know if it's this rule, but it's related to your comment => "could relate to a * and + in the same rule"

I have to do some tests before being able to say which rule generate this issue ( Identifier '_alt' has already been declared )

**Comment by ericvergnaud** [comment] 2020-12-03 16:46
there is no * or + in your rule (I'm referring to ANTLR operators * and +, not characters '*' and '+')

**Comment by XStepien** [comment] 2020-12-03 16:51
Ok, sorry for the misunderstanding,I will try to find more information soon

**Comment by dbemiller** [comment] 2020-12-04 19:07
I'm also seeing this. I can't post the whole grammar for IP reasons, but I do have a few tricky rules with `+` and `*` in them:

```
nestedPredicate :
    comparison
  | L_PAREN nestedPredicate (SPACE (OR_UPPER | OR_LOWER) SPACE nestedPredicate)+ R_PAREN
  | L_PAREN nestedPredicate (SPACE (AND_UPPER | AND_LOWER) SPACE nestedPredicate)+ R_PAREN
  ;

nestedMathable :
    integer
  | decimal
  | column
  | L_PAREN nestedMathable SPACE DIVIDE SPACE nestedMathable R_PAREN
  | L_PAREN nestedMathable SPACE MINUS SPACE nestedMathable R_PAREN
  | L_PAREN nestedMathable SPACE PLUS SPACE nestedMathable (SPACE PLUS SPACE nestedMathable)* R_PAREN
  | L_PAREN nestedMathable SPACE TIMES SPACE nestedMathable (SPACE TIMES SPACE nestedMathable)* R_PAREN
  ;
```

Hope this helps. If not I can start deleting/anonymizing names to try to get a minimum reproducible one that I can share without giving up proprietary stuff.

**Comment by ericvergnaud** [comment] 2020-12-05 08:20
can you paste the generated fragment causing the trouble?

**Comment by dbemiller** [comment] 2020-12-07 13:47
ahh... yeah now that I'm looking at the generated code, it's much clearer. The `nestedPredicate()` and `nestedMathable()` functions do _not_ have the error, so ignore my last comment.

My plain old mathable() rule does, though:

```
mathable() {
  ...
  try {
    ...
    case 6:
      ...
      let _alt = this._interp.adaptivePredict(this._input,19,this._ctx)
      ...
    case 7:
      ...
      let _alt = this._interp.adaptivePredict(this._input,20,this._ctx)
      ...
}
```

Issue being that `let` declares the same var twice within the same block scope. The rule in my `g4` file looks like:

```
mathable :
    integer
  | decimal
  | column
  | nestedMathable SPACE DIVIDE SPACE nestedMathable
  | nestedMathable SPACE MINUS SPACE nestedMathable
  | nestedMathable SPACE PLUS SPACE nestedMathable (SPACE PLUS SPACE nestedMathable)*
  | nestedMathable SPACE TIMES SPACE nestedMathable (SPACE TIMES SPACE nestedMathable)*
  ;
```

So... it looks like the issue is with _non_-recursive `*` rules. Recursive ones are ok.

**Comment by ericvergnaud** [comment] 2020-12-08 00:11
In https://github.com/antlr/antlr4/commit/c87e55b6111318ad173f505fe1b2cb722b1b9d42 I've switched let _alt... to var ...alt
It would help if you could try it out and tell if that fixes the issue

**Comment by dbemiller** [comment] 2020-12-08 18:34
That should also be fine. `let` is spec'd to [throw a SyntaxError when you re-declare it](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) (see the "Redeclarations" section).

`var` is not: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var

> Duplicate variable declarations using var will not trigger an error, even in strict mode, and the variable will not lose its value, unless another assignment is performed.

**Comment by dbemiller** [comment] 2020-12-08 18:49
followup: just tested by following the instructions [here](https://github.com/antlr/antlr4/blob/master/doc/building-antlr.md) on your commit. It builds & runs fine again for me.

Not sure what antlr's release schedule is... any estimate on how long it'll be until a patch version gets released with the fix?

**Comment by XStepien** [comment] 2021-01-12 10:56
Hello,

I just upgraded to version 4.9.1 and everything works fine now.

Thanks a lot!

**Closed** 2021-01-12 10:59 UTC
Labels: target:javascript

**Comment by danielleallopez** [comment] 2021-06-04 09:38
Hello. I've seen this same issue reproduce in version 4.9.2, with a similar grammar (includes a recursive expr). Can it be that it has been reintroduced? Thanks!
