### ISSUE TITLE
 no viable alternative at input '..'

### ISSUE THREAD

**Issue by Morgaroth** [antlr/antlr4#546] opened 2014-04-13 22:43 UTC
why?
I've grammar:

```
    grammar Regulars;
    start : test ;
    test : 'a' .. 'z';
```

and can't generate anything:
 log https://gist.github.com/Morgaroth/10605312
I'm using antlr-4.2.2-complete.jar

**Comment by KvanTTT** [comment] 2017-05-18 22:03
@parrt it's a duplicate of #1556. Now should be closed too.

**Closed** 2017-05-19 15:54 UTC
Labels: comp:tool, type:bug
