### ISSUE TITLE
Parenthesis expression not returning expected result

### ISSUE THREAD

**Issue by gdromard** [antlr/antlr4#1278] opened 2016-09-08 18:40 UTC
I'm testing this antlr grammar with version 4.5.3
and with the input `(1+1)`

But the result is not the expecting one !
Is this a bug or did I made a mistake ?

``` antlr
/** Grammar from tour chapter augmented with actions */
grammar Expr;

@header {
    import java.util.*;
}
@parser::members {
    Map<String, Object> variables = new HashMap<String, Object>();
}

parse returns [Object v]: command* EOF { $v = $command.v; };

command returns [Object v]
    : LBRACE command RBRACE     { $v = $command.v; }
    | expr                      { $v = $expr.v; }
    | cond                      { $v = $cond.b; }
    | declare                   { $v = $declare.v; }
    | string                    { $v = $string.s; }
;

declare returns [Object v]
    : NUMBER_FIELD '=' n=expr   { $v = $n.v; variables.put($NUMBER_FIELD.text, $n.v); }
    | BOOL_FIELD   '=' b=cond   { $v = $b.b; variables.put($BOOL_FIELD.text, $b.b); }
    | STRING_FIELD '=' s=STRING { $v = $s.text; variables.put($STRING_FIELD.text, $s.text); }
;

string returns [String s]
    : STRING                    { $s = $STRING.text; }
    | id=STRING_FIELD           { $s = variables.containsKey($id.text) ? (String) variables.get($id.text) : ""; }
;

expr returns [double v]  // l'expression à analyser sera soit une addition, une soustraction, une multiplication ou une division
    : a=expr PRODUCT b=expr     { $v = $a.v * $b.v; }
    | a=expr DIV b=expr         { $v = $a.v / $b.v; }
    | a=expr PLUS b=expr        { $v = $a.v + $b.v; }
    | a=expr MINUS b=expr       { $v = $a.v - $b.v; }
    | MINUS NUMBER              { $v = -Double.parseDouble($NUMBER.text); }
    | NUMBER                    { $v =  Double.parseDouble($NUMBER.text); }
    | id=NUMBER_FIELD           { $v = (Double) (variables.containsKey($id.text) ? variables.get($id.text) : 0.0); }
;


cond returns [boolean b]    // Boolean Expresion
    : ea=expr GT ez=expr        { $b = $ea.v >  $ez.v; }
    | ea=expr GE ez=expr        { $b = $ea.v >= $ez.v; }
    | ea=expr LT ez=expr        { $b = $ea.v <  $ez.v; }
    | ea=expr LE ez=expr        { $b = $ea.v <= $ez.v; }
    | ea=expr EQ ez=expr        { $b = $ea.v == $ez.v; }
    | sa=string EQ sb=string    { $b = $sa.s.equals($sb.s); }
    | NOT cond                  { $b = !$cond.b; }
    | a=cond AND z=cond         { $b = $a.b && $z.b; }
    | a=cond OR z=cond          { $b = $a.b || $z.b; }
    | TRUE                      { $b = true; }
    | FALSE                     { $b = false; }
    | id=BOOL_FIELD             { $b = (Boolean) (variables.containsKey($id.text) ? variables.get($id.text) : false); }
;


comparator  : GT | GE | LT | LE | EQ;

binary      : AND | OR;

bool        : TRUE | FALSE;


AND          : 'AND' ;
OR           : 'OR' ;
NOT          : 'NOT';
TRUE         : 'TRUE' ;
FALSE        : 'FALSE' ;

GT           : '>' ;
GE           : '>=' ;
LT           : '<' ;
LE           : '<=' ;
EQ           : '==' ;

PLUS         : '+' ;
MINUS        : '-' ;
PRODUCT      : '*' ;
DIV          : '/' ;

LBRACE       : '(';
RBRACE       : ')';

NUMBER       : [0-9]+ ( '.' [0-9]+ )?;
ESC_SEQ      : '\\' ('b'|'t'|'n'|'f'|'r'|'\"'|'\''|'\\');
STRING       : '""' |   '"' (ESC_SEQ | ~('\\'|'"'))+ '"';
BOOL_FIELD   : ('b') ('A'..'Z') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
NUMBER_FIELD : ('d') ('A'..'Z') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;
STRING_FIELD   : ('a'..'z') ('a'..'z'|'A'..'Z'|'0'..'9'|'_')*;


WS      // cette règle permet de reconnaître les espacements
   :
    ( ' '
    | '\t'
    | '\r' '\n'
    | '\n'
    )
 -> skip // ne pas considérer ces espacements comme tokens
;
```

My Java Test Code is

``` java
        System.out.println("Starting Expr console:");
        String inputFile = null;
        if ( args.length>0 ) inputFile = args[0];
        InputStream is = System.in;
        if ( inputFile!=null ) {
            is = new FileInputStream(inputFile);
        }

        BufferedReader br = new BufferedReader(new InputStreamReader(is));
        String expr = br.readLine();              // get first expression
        int line = 1;                             // track input expr line numbers

        ExprParser parser = new ExprParser(null); // share single parser instance
        //parser.setBuildParseTree(false);          // don't need trees

        while ( expr!=null ) {             // while we have more expressions
            // create new lexer and token stream for each line (expression)
            ANTLRInputStream input = new ANTLRInputStream(expr+"\n");
            ExprLexer lexer = new ExprLexer(input);
            lexer.setLine(line);           // notify lexer of input position
            lexer.setCharPositionInLine(0);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            parser.setInputStream(tokens); // notify parser of new token stream
            parser.getBuildParseTree();
            ExprParser.ParseContext parseCtx = parser.parse();
            System.out.println(parseCtx.toStringTree(parser));
            // start the parser and print result
            System.out.printf("%-70s -> %s\n", expr, parseCtx.v);
            expr = br.readLine();          // see if there's another line
            line++;
        }
```

**Comment by parrt** [comment] 2016-11-25 20:57
likely duplicate of https://github.com/antlr/antlr4/issues/1295

**Closed by parrt** 2016-11-25 20:57 UTC
Labels: status:duplicate
