### ISSUE TITLE
Make ParserRuleContext Serializable!!

### ISSUE THREAD

**Issue by T0bi-Ethirbirge** [antlr/antlr4#2297] opened 2018-05-25 15:54 UTC
You are doing a great job keep up the good work.
Can you please make ParserRuleContext Serializable. Target [c#]
I tried but i ended up with an **exception**  "Type system.io.__consolestream is not marked as serializable in mscorlib"
## I'm not Serializting it for performance it's for something else.
I hope you guys replay.

**Comment by sharwell** [comment] 2018-05-25 16:23
Probable duplicate of #233. It's unlikely that this will be fixed. Aside from the compatibility impact of such a change, the comment https://github.com/antlr/antlr4/issues/233#issuecomment-310778436 applies - the objects cannot be guaranteed to only contain serializable types.

**Closed** 2018-09-05 19:03 UTC
