### ISSUE TITLE
[Go target] Antlr Visitor does not work properly

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4398] opened 2023-08-28 19:15 UTC
The Visitor tree walker for the Go target does not seem to work properly, at least how it works in comparison to all the other targets. This is a continuation of https://github.com/antlr/antlr4/issues/4395. I don't know why that was closed, the [initial comment completely erased](https://github.com/antlr/antlr4/issues/4395#issue-1867986623), and https://github.com/antlr/antlr4/issues/4404 opened. In any case, https://github.com/antlr/antlr4/issues/4398 is a detailed analysis on the Visitor code for the Go target.

Starting with the original grammar, I added debugging output to all visitor code "derived" in the parent struct of "BaseExprVisitor" (aka "Visitor"), the "BaseExprVisitor" struct, and the structs and functions in the Antlr4 Go runtime. The "workaround" (`func (v *Visitor) Visit(t antlr.ParseTree) any` ), which is claimed to fix the problem of getting  `func (v *Visitor) VisitStart(ctx *parser.StartContext) any` to be called, does not really fix the issues with the Visitor code. The problem goes far beyond that. Replacing the `VisitStart()` function with a `VisitExpr()` or `VisitDecl()` function shows that the "work-around" does not work because `VisitExpr()` or `VisitDecl()` are not called. *The default implementation generated by the Antlr tool does not actually traverse the parse tree!* You can test this by simply adding debugging output to the generated "Visit" functions for Visit, BaseExprVisitor, and BaseParseTreeVisitor and see for yourself.

For an example that does work, see https://github.com/kaby76/antlr-4395. But, this implementation is not what I expected.

I am not clear what the Visitor code is supposed to look like. There is no example in the documentation. 

## VisitChildren() does not have an implementation
For all targets except Go, the base class code has an implementation that loops through all children of a node and calls Visit() on the child. There is no function like this anywhere in the Antlr Go runtime, nor is it generated by the tool. The Antlr tool generates code that contains VisitChildren() function calls.
```
func (v *BaseExprVisitor) VisitProg(ctx *ProgContext) interface{} {
	return v.VisitChildren(ctx)
}
```
For all targets, the code does exactly what is expected.
* CSharp. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/CSharp/src/Tree/AbstractParseTreeVisitor.cs#L44-L59
* Cpp. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Cpp/runtime/src/tree/AbstractParseTreeVisitor.h#L35-L48
* Dart. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Dart/lib/src/tree/src/tree.dart#L117-L131
* Java. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Java/src/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.java#L37-L51
* JavaScript/TypeScript. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/JavaScript/src/antlr4/tree/ParseTreeVisitor.js#L6-L22
* Python3. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Python3/src/antlr4/tree/Tree.py#L36-L47
* Swift. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Swift/Sources/Antlr4/tree/AbstractParseTreeVisitor.swift#L33-L48
* PHP (*no 4.13.0 release; does not work with 4.13). https://github.com/antlr/antlr-php-runtime/blob/1ebacfd8a9761dc14509c305887d43899f1e18c5/src/Tree/AbstractParseTreeVisitor.php#L39-L59

For Go, the only function that defines VisitChildren() is:
```
func (v *BaseParseTreeVisitor) VisitChildren(_ RuleNode) interface{}     { return nil }
```
*I have to conclude that the Visitor code cannot work as is because there is no implementation for VisitChildren(). One must implement the function for Go.*

## Unclear how to define the derived Visitor struct--or interface
To use the code, all functions need to be defined for the composite visitor struct.

Is it this?
```
type Visitor struct {
    *parser.BaseExprVisitor
}
```
Or this?
```
type Visitor struct {
    parser.BaseExprVisitor
}
```
Or this?
```
type Visitor struct {
    parser.ExprVisitor
}
```
In any of these implementations, one needs to define every function associated with the visitor: Visit(), VisitChildren(), VisitProg(), VisitDecl(), VisitExpr(), VisitTerminal(), VisitErrorNode(). Otherwise, it either doesn't work or crashes.

*In order to get the code to work, I essentially needed to reimplement the entire code from scratch.* 

*If this is true, then this is a significant departure from how most people would understand how the code should work. Yes, Go does not support Inheritance. All the more, the documentation should provide an explicit, working example, complete with driver, grammar, visitor, go.mod, and makefile.*

*Personally, I don't use the Visitor code because semantic analysis is better served with the Listener code (for LR-attribute analysis), which people also claim to work.*

**Comment by jimidle** [comment] 2023-08-30 02:37
On vacation right now. I’ll look when I get back, but it works fine for me.
Go may not always copy the other targets though

**Comment by mkohlhaas** [comment] 2023-09-04 11:44
> * CSharp. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/CSharp/src/Tree/AbstractParseTreeVisitor.cs#L44-L59
> * Cpp. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Cpp/runtime/src/tree/AbstractParseTreeVisitor.h#L35-L48
> * Dart. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Dart/lib/src/tree/src/tree.dart#L117-L131
> * Java. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Java/src/org/antlr/v4/runtime/tree/AbstractParseTreeVisitor.java#L37-L51
> * JavaScript/TypeScript. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/JavaScript/src/antlr4/tree/ParseTreeVisitor.js#L6-L22
> * Python3. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Python3/src/antlr4/tree/Tree.py#L36-L47
> * Swift. https://github.com/antlr/antlr4/blob/a27cf84839c4f794e43b83b9b922d9342367fe45/runtime/Swift/Sources/Antlr4/tree/AbstractParseTreeVisitor.swift#L33-L48
> * PHP (*no 4.13.0 release; does not work with 4.13). https://github.com/antlr/antlr-php-runtime/blob/1ebacfd8a9761dc14509c305887d43899f1e18c5/src/Tree/AbstractParseTreeVisitor.php#L39-L59

I guess all the other languages have proper class/object inheritance and method overloading. Golang has only embedding and interfaces. Makes it much more difficult to write a port from Java.

**Comment by kaby76** [comment] 2023-09-08 10:42
https://groups.google.com/g/antlr-discussion/c/gEiAPs-XGps

I cannot see how this person's code targeted for Go can work whatsoever. I have not replied there because the Google Antlr Discussion Group is only for announcements (but we haven't seen Antlr 4.13.1 announced either).

**Comment by cwarden** [comment] 2023-11-28 00:53
@thesues provides a [working example](https://github.com/thesues/antlr-calc-golang-example/blob/master/visitor/main.go), (updated to antlr 4.13 in https://github.com/cwarden/antlr-calc-golang-example/blob/master/visitor/main.go) that looks like this:

```
type Visitor struct {
	parser.BaseCalcVisitor
}

func (v *Visitor) visitRule(node antlr.RuleNode) interface{} {
	node.Accept(v)
	return nil
}

func (v *Visitor) VisitStart(ctx *parser.StartContext) interface{} {
	return v.visitRule(ctx.Expression())
}
...
func main() {
	is := antlr.NewInputStream(input)

	// Create the Lexer
	lexer := parser.NewCalcLexer(is)
	tokens := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)

	// Create the Parser
	p := parser.NewCalcParser(tokens)

	v := &Visitor{}
	v.Start_().Accept(v)
}
```

**Comment by kaby76** [comment] 2023-11-28 01:08
@cwarden That example illustrates my point. Every single production in the grammar requires an implementation of the visit function. If you do not implement the `VisitStart()` function, then the expression nodes are never visited. For all other targets, that is not the case because there is an implementation for VisitChildren(). There is none in the Go runtime. For a toy example like Calc.g4, implementing a handful of extra visitor functions in the chain of notes from the root is not hard. But, for a large grammar with hundreds of rules, this becomes an issue.

**Comment by mburbidg** [comment] 2024-01-24 03:13
One other thing. Error handling is very awkward! The visitor methods should all return (interface{}, error). This code is very Java-centric, and doesn't appear to be written with a deep understanding of Go.

**Comment by jimidle** [comment] 2024-01-24 08:46
It wasn’t originally my code, but I assure you it works as I have used it
in anger as well as the walker. I also assure you I’m that I understand Go,
though the original author was very new to it.

**Comment by mkohlhaas** [comment] 2024-01-24 09:45
> One other thing. Error handling is very awkward! The visitor methods should all return (interface{}, error). This code is very Java-centric, and doesn't appear to be written with a deep understanding of Go.

Please be constructive. A lot of code had to be written for this library. I appreciate the effort a lot!

**Comment by mburbidg** [comment] 2024-01-24 18:19
I apologize, for my un-constructive comment.

I don't doubt that it works. And I appreciate the work that went into it. I think what is at issue is the WAY it works. Some very constructive suggestions have been made in this thread and some valid reasons as to why the way the code currently works is much less than ideal. Including the fact that the current implementation does not account for how error handling is done in Go. This applies to the listener as well as the visitor.

I would be willing to do some incremental work on this to improve it. It is unclear to me whether improvements would be considered or not. I don't want to do a lot of work, submit a PR and then have it rejected out of hand.

Is there a process for proposing a change, that is then discussed, and agreed to before work begins? I imagine that one of the issues is backwards compatibility. Is the runtime versioned, so that folks could adopt the changes as needed?

I would suggest making changes in stages. The first PR would be to change the return type of both the listener and visitor to include an error. The second would be to include default behavior to the visitor, similar to the default behavior present in some of the other implementations. Of course this cannot be done via inheritance, but there are other ways to do it in Go.

What do you think?

**Comment by ycl2018** [comment] 2024-05-10 03:29
hey! i fixed this problem in my [repo](https://github.com/ycl2018/pie-go) , just replace the field of BaseParseTreeVisitor to interface antlr.ParseTreeVisitor in the generated file [pie_base_visitor.go](https://github.com/ycl2018/pie-go/blob/main/gen/pie_base_visitor_modify.go). I rename this file to pie_base_visitor_modify.go in my repo, and use my own [BaseParseVisitor](https://github.com/ycl2018/pie-go/blob/main/tree/basevisitor.go) which implements antlr.ParseTreeVisitor!, it works well!

**Comment by jimidle** [comment] 2024-05-10 22:20
You should not need to change the generated code. I have a dozen visitors. You need to embed the generated base visitor in your own struct and go from there. I still have not had time to make a demo of this.

Jim

**Comment by ycl2018** [comment] 2024-05-11 02:50
@jimidle Yes, I shouldn't have modified the generated code. But I can't complete my Visitor through other means. I think this should be a problem with the implementation of antlr4 go runtime. The generated BaseVisitor has a *BaseParseTreeVisitor field embedded in it which is a struct rather than interface{}(what i do in my repo is to fix this), so any implementation that 'inherits' BaseVisitor cannot really override its VisitChildren() or other methods.  and *BaseParseTreeVisitor does not implement methods other than the Visit method, so it cannot be used at all.

As you mentioned, in the Java version implementation, the BaseVisitor inherits AbstractParseTreeVisitor, which has a complete implementation of VisitChildren and so on other methods. And users can implement custom methods by overriding its methods.

**Comment by jimidle** [comment] 2024-05-11 20:58
Go is not Java. There is no need for an interface. All you do is this (Listener here but it is the same):

```go
// Listener is a listener that collects information about the program and performs a kind of
// lint analysis.
type Listener struct {
	parsing.BaseMVBListener. // Go is NOT Java. There is no inheritence
	errCount int
        // Whatever else you want in your Listener
}

func (s *Listener) HasErrors() bool {
	return s.errCount > 0
}

func (t *Listener) EnterEveryRule(ctx antlr.ParserRuleContext) {
	// fmt.Println("Entering rule", ctx.GetRuleIndex(), "at line", ctx.GetStart().GetLine(), "col", ctx.GetStart().GetColumn())
}

func (t *Listener) ExitEveryRule(ctx antlr.ParserRuleContext) {
	//fmt.Println("Exiting rule", ctx.GetRuleIndex(), "at line", ctx.GetStart().GetLine(), "col", ctx.GetStart().GetColumn())
}

func (t *Listener) ExitTunit(ctx *parsing.TunitContext) {
  // Overrides generated base func
  }
  
lexer.SetInputStream(t.InStream)
tokstream.SetTokenSource(t.Lexer)
parser.SetTokenStream(t.TokStream)
tree := parser.TranslationUnit()
// check errors
antlr.ParseTreeWalkerDefault.Walk(&Listener{}, tree)

**Comment by jimidle** [comment] 2024-05-11 21:08
The embedded * of the abstract visitor is wrong, (shoudl not be a pointer) but for reasons that I cannot now remember I decided not to fix that. I think too much of the runtime expected it to be a pointer. I probably have a note somewhere telling me to fix it at some point.

But all you need do is embedded in your various vistors and start accept() ing. 


```go
// Code generated from MVB.g4 by ANTLR 4.12.0. DO NOT EDIT.

package parsing // MVB
import "github.com/antlr4-go/antlr/v4"

type BaseMVBVisitor struct {
	*antlr.BaseParseTreeVisitor
}

func (v *BaseMVBVisitor) VisitTranslationUnit(ctx *TranslationUnitContext) interface{} {
	return v.VisitChildren(ctx)
}
...

type MyVisitor struct {
  BaseMVBVisitor
}

func (v * MyVisitor) VisitTranslationUnit(ctx * TranslationUnitContext) someresult {
  x = ctx.something.accept(v)
  // do something
  // return the reult you want
}

And so on.
```

**Comment by mburbidg** [comment] 2024-05-18 04:10
I would like to give this one more shot. I am building a grammar and front-end for a very large language. I want to use the Visitor pattern, not the Listener because of the flexibility it provides in controlling the visit path and error handling. Many of my Visit methods look as follows:

```
func (v *Visitor) VisitLinearCatalogModifyingStatementAlt(ctx *gen.LinearCatalogModifyingStatementAltContext) interface{} {
	return ctx.LinearCatalogModifyingStatement().Accept(v)
}
```
These nodes have a single child and essentially call Accept on that single child.

To remove a lot of boilerplate code, I'd like to be able to provide a VisitChildren method that is used by default, if a more specific method is not provided. It would look something like this:

func (v *Visitor) VisitChilrdren(ctx *?) interface{} {
    return ctx.Child(0).Accept()
}

The Go runtime looks like it was designed to enable this, but as it is currently constructed it does not. You have to provide an implementation of every single Visit Method. There's no default traversal and you cannot provide a default traversal, without modifying generated code. I believe this is what the original author was trying to convey as well as the fact that the other runtimes provide this capability.

A default implementation of this method is provided on the antlr.BaseParseTreeVisitor as follows.

```
func (v *BaseParseTreeVisitor) VisitChildren(_ RuleNode) interface{}     { return nil }
```
I believe if you moved this default implementation to the generated base class (e.g. BaseMVBVisitor) then it could be overriden in my visitor (e.g. MyVisitor).

**Comment by jimidle** [comment] 2024-05-18 17:18
There is no need to provide an implementation of every visit function. The default in the base visitor should accept automatically on. its children. I am afraid I don't have time to create a full example. I think you can override visitChildren, but IIRC that just calls accept on the children. I am not sure it would be that useful to try and do everything in that func.

Maybe you can provide your code to me (privately if you wish) and I can see what you are trying to achieve. 

To the person asking for an error signature - while that is indeed a common pattern in Go, it is not how you walk parser trees. Create an error collector and make it avaiable in the struct that embeds BaseVisitor, you can also create nodes that mark errors and unresolved. Remember that this is a parse tree walker - generally, you would construct some kind of AST using it. Don't throw exceptions or return errors in the walker. 

At some point I would like to generate a generic visitor and listener. I touched the listener and visitor the least in the huge changes made to make the runtime work. It probably is time to give the walkers some attention.

```antlr

type JimVisitor struct {
        // Base generated by ANTLR
	parsing.BaseMVBVisitor
	// Add things like an error collector here
}

func (v *JimVisitor) VisitChildren(node antlr.RuleNode) interface{} {
       // This is what the default implementation does, I just added a print
	fmt.Println("Visiting children. Rule", node.GetRuleContext().GetRuleIndex())
	return v.BaseMVBVisitor.VisitChildren(node)
}

// Override any other visitors here - this example is from a working compiler
```

**Comment by jimidle** [comment] 2024-05-18 17:19
@parrt - let's close this - I have supplied a number of examples and at some point I will create a full working repo.

**Closed** 2024-05-18 19:24 UTC

**Comment by jimidle** [comment] 2024-05-18 20:41
One final comment though...

I have just implemented the visitor and listener with Generics, fixed the interface definitions and fixed the generation of that stupid pointer. It will be another day or so before I push that to the development branch and the main tree. I guess I will give in and also get rid of the exp imports ;)

**Comment by mburbidg** [comment] 2024-05-18 22:00
I'm not sure why this does not work for me. As far as I can see, I'm am set up just as in your example. But for me, VisitChildren is never called. Here's is my visitor:

```
package parser

import (
	"fmt"
	"github.com/antlr4-go/antlr/v4"
	"github.com/mburbidg/mygql/gql/parser/ast"
	"github.com/mburbidg/mygql/gql/parser/gen"
	"github.com/mburbidg/mygql/utils"
	"strconv"
	"strings"
)

type Visitor struct {
	gen.BaseGQLVisitor
}

func NewVisitor() gen.GQLVisitor {
	return &Visitor{}
}

func (v *Visitor) VisitChildren(node antlr.RuleNode) interface{} {
	fmt.Println("Visiting children. Rule", node.GetRuleContext().GetRuleIndex())
	return v.BaseGQLVisitor.VisitChildren(node)
}
...
// Root of the tree visit function
func (v *Visitor) VisitGqlProgram(ctx *gen.GqlProgramContext) interface{} {
	pgm := &ast.GQLProgram{}
	if ctx.ProgramActivity() != nil {
		activity := ctx.ProgramActivity().Accept(v)
		pgm.Activity = activity
	}
	if ctx.SessionCloseCommand() != nil {
		pgm.CloseOnCompletion = true
	}
	return pgm
}
```
Here's my code that invokes the parser and calls visits the resulting tree.
```
	src := `CREATE SCHEMA IF NOT EXISTS /mymovies`
	input := antlr.NewInputStream(src)
	lexer := gen.NewGQLLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, 0)
	p := gen.NewGQLParser(stream)
	errListener := newErrorListener()
	p.AddErrorListener(errListener)
	p.BuildParseTrees = true
	tree := p.GqlProgram()
	assert.Equal(t, 0, len(errListener.errors))
	visitor := NewVisitor()
	tree.Accept(visitor)
```

**Comment by YuriyKortev** [comment] 2024-06-02 17:15
There are a lot of words in this discussion, but in fact the visitor does not work for Go.

> There is no need to provide an implementation of every visit function.`

If some visit function not implemented, it will call generated method which call `BaseParseTreeVisitor.VisitChildren` which do nothing. Custom `VisitChildren` implementation will not help, because generated visitor knows nothing about custom visitor which embeds it.

**Comment by jimidle** [comment] 2024-06-03 18:27
Yes standby for some updates

**Comment by onsi** [comment] 2024-10-02 01:01
@jimidle (gentle nudge) - any updates on this?  Do you have ideas/direction for a PR?  Perhaps some of us following this thread could contribute a fix?

**Comment by JoshSharpe** [comment] 2024-10-13 16:56
> I have a fix and a huge reduction in generated code but have not had time to complete it for release. It will be done before the next release. But it is not practical to use generics in the walker as go doesn’t have double dispatch
> […](#)

I've just started looking into how the code works to try to put up a PR and wanted to share a few thoughts. Hopefully as a summary of the above comments. 

I think the patch can be broken down into parts:
1. The visitChildren baked in should include some default behavior that checks for children and visits each. Here is a simple example:
```
	results := []interface{}{}
	children := node.GetChildren()
	for _, child := range children {

		termNode, ok := child.(TerminalNode)
		if ok {
			fmt.Println("termNode: ")
			newRes := v.Visit(termNode)
			results = append(results, newRes)
			continue
		}

		ruleNode, ok := child.(RuleNode)
		if ok {
			fmt.Println("ruleNode: ")

			newRes := v.Visit(ruleNode)
			results = append(results, newRes)
			continue
		}
	}
	fmt.Println("results: ", results)

	return results
```

I have shown in my local that this will help visit each child node. However, there are still issues so I haven't yet created a PR. 

2. Overwriting a single visitor node does not get picked up. This is because the visitor is using the "lower-level" object to determine what to do. This problem is harder to resolve because it is architectural. It's why people mention they have to re-write each node. In fact, the code above that would exist in `tree.go` right now would call the Visit/Accept method defined there. It would not even call the generated base code, much less the user-defined code on top of the generated code.

I believe this means that the `ParseTreeVisitor` may have to be part of the generated base_visitor code as well. By moving the `VisitChildren` to the base visitor it correctly calls. This still does not truly enable "overwrites" of the base function since it is referring to the lower type.

Sorry this does not offer any direct help or solutions. I am happy to help make code changes @jimidle but it seems you are currently doing it. If you'd like help feel free to post where you are or some docs that explain the direction you'd prefer. 
 
It's a tricky problem to solve in go. I think the generated base_visitor struct has to also be used directly. Meaning that the pattern may be to generate the code as-is but any overwrite occur in the same package by moving the method into an impl file. Anytime code generation occurs again that method would have to be removed.

**Comment by jimidle** [comment] 2024-10-14 19:29
Yes. I have domne all this.
