### ISSUE TITLE
C# GetText missing blanks

### ISSUE THREAD

**Issue by lrs5** [antlr/antlr4#836] opened 2015-03-16 21:32 UTC
In the C# version of Antlr.Runtime.RuleContext, method GetText, the code reads

            for (int i = 0; i < ChildCount; i++)
            {
                builder.Append(GetChild(i).GetText());
            }
            return builder.ToString();

It should have builder.Append(" "); after builder.Append(GetChild(I).GetText());

Otherwise, the text all runs together.

**Comment by ericvergnaud** [comment] 2015-03-17 02:02
Hi,
am I correct in thinking that the reason whitespace isn't printed is because your lecture redirects whitespace to an hidden channel?

**Comment by lrs5** [comment] 2015-03-17 03:17
Thanks for trying to help, but I don't think so. I admit that at one 
point my grammar did use a hidden channel for whitespace, but I've been 
trying a lot of things and there currently is no hidden channel stuff.

My current best guess is that while at the point I filed the bug report, 
I was skipping white space (via -> skip). So while I didn't try the 
following test, I suspect that "a b c" (no quotes) would have displayed 
as "abc" (still no quotes). Which really doesn't strike me as correct.

I'm currently treating white space as significant and things are coming 
out as "a b c".

BTW, the original discrepancy was the result of ToStringTree Snippet

**Comment by ericvergnaud** [comment] 2015-03-17 12:36
mmm
your experience seems to confirm my analysis, so I will close this.
feel free to reopen if you can reproduce.

**Closed by ericvergnaud** 2015-03-17 12:36 UTC
