### ISSUE TITLE
Golang target extremly slow, while Java target is fast on same input

### ISSUE THREAD

**Issue by Lacuno** [antlr/antlr4#2152] opened 2017-12-07 12:38 UTC
I need to parse MySQL for a project and use https://github.com/antlr/grammars-v4/tree/master/mysql
this grammar with the newest ANTLR from the master branch (4.7.1-SNAPSHOT).
On certain queries the parser spends a lot of time in the golang target (25-27sec), while the Java target is much faster (700ms-1sec). The IntelliJ Plugin even parses faster (~300ms).
Example query: 
  
    SELECT SUM((IFNULL(X, 0) - IFNULL(Y, 0) - IFNULL(Z, 0) - (IFNULL(XX, 0) - IFNULL(YY, 0) - IFNULL(ZZ, 0))) * IFNULL(ASDF, 0)) AS `REVENUE` FROM SALES_FLAT

I used SLL PredicionMode on both targets, but that does not help.
I also ran the query multiple times, but warming up also didn't help much.
Afterwards I profiled the Go target and got the following output for my query mentioned above:

      flat  flat%   sum%        cum   cum%
    5980ms 14.28% 14.28%    16020ms 38.26%  runtime.scanobject C:\dev\Go\src\runtime\mgcmark.go
    4970ms 11.87% 26.15%     5430ms 12.97%  runtime.heapBitsForObject C:\dev\Go\src\runtime\mbitmap.go
    3280ms  7.83% 33.99%     8070ms 19.27%  github.com/antlr/antlr4/runtime/Go/antlr.(*BaseSingletonPredictionContext).hash C:\dev\projects\go\src\github.com\antlr\antlr4\runtime\Go\antlr\prediction_context.go
    2620ms  6.26% 40.24%     2620ms  6.26%  github.com/antlr/antlr4/runtime/Go/antlr.murmurUpdate C:\dev\projects\go\src\github.com\antlr\antlr4\runtime\Go\antlr\utils.go (inline)
    2070ms  4.94% 45.19%     2070ms  4.94%  github.com/antlr/antlr4/runtime/Go/antlr.murmurFinish C:\dev\projects\go\src\github.com\antlr\antlr4\runtime\Go\antlr\utils.go (inline)
    1240ms  2.96% 48.15%     1240ms  2.96%  runtime.markBits.isMarked C:\dev\Go\src\runtime\mbitmap.go (inline)
     980ms  2.34% 50.49%     1540ms  3.68%  runtime.evacuate C:\dev\Go\src\runtime\hashmap.go
     960ms  2.29% 52.78%      960ms  2.29%  runtime.spanClass.noscan C:\dev\Go\src\runtime\mgcmark.go (inline)
     870ms  2.08% 54.86%     3650ms  8.72%  runtime.greyobject C:\dev\Go\src\runtime\mgcmark.go
     840ms  2.01% 56.87%     1000ms  2.39%  runtime.heapBitsSetType C:\dev\Go\src\runtime\mbitmap.go

Of course the grammar is not optimized, but still the difference between the targets is tremendous.

**Comment by parrt** [comment] 2017-12-07 17:56
I just merged some hash code changes from @davesisson. can you pull and try again?

**Comment by davesisson** [comment] 2017-12-07 17:57
One of those changes was a change to the hashing code (which you've listed
above).  It's not any faster than before, but it might be more correct
(which could affect your behavior).

**Comment by neatnerd** [comment] 2017-12-08 23:14
@parrt, I have tried with the update from @davesisson, no changes

**Comment by parrt** [comment] 2017-12-08 23:15
@neatnerd sorry to hear that. dang! it's usually a hash code issue.

**Comment by neatnerd** [comment] 2017-12-08 23:32
@parrt there are 3 issues I suspect:

1.  inefficient memory management due to constant casts
1.  improvements to hash calculation
1.  parser atn simulator that I dont understand

check out the [graph](https://drive.google.com/file/d/1qxsDIe2W97wKDGnnA21WOsX0dE_DV41W) (svg, download)

**Memory**:

This calls might cause a problem, because if I correctly understand GO memory model, during these casts, every time a new variable (memory allocated), so _scanobject_ goes crazy:

```go
func murmurUpdate(h1 int, k1 int) int {
	var k1u uint
	k1u = uint(k1) * c1_32
	k1u = rotateLeft(k1u, 15)
	k1u *= c2_32

	var h1u = uint(h1) ^ k1u
	k1u = rotateLeft(k1u, 13)
	h1u = h1u*5 + 0xe6546b64
	return int(h1u)
}
```

unit <-> int is a bad idea, also shown by profiling


     100ms      100ms    395:func murmurUpdate(h1 int, k1 int) int {
         .          .    396:   var k1u uint
     290ms      290ms    397:   k1u = uint(k1) * c1_32
         .          .    398:   k1u = rotateLeft(k1u, 15)
     420ms      420ms    399:   k1u *= c2_32
         .          .    400:
     140ms      140ms    401:   var h1u = uint(h1) ^ k1u
         .          .    402:   k1u = rotateLeft(k1u, 13)
     340ms      340ms    403:   h1u = h1u*5 + 0xe6546b64
     410ms      410ms    404:   return int(h1u)


400 ms for `return int(h1u)` ?

**Hash Calculation**

[this](https://github.com/spaolacci/murmur3) implementation seems efficient, we will try it

**ATN Simulator**

Like I said, no idea, maybe this helps

```
ROUTINE ======================== github.com/antlr/antlr4/runtime/Go/antlr.(*ParserATNSimulator).closureWork in C:\dev\shadowsong\src\github.com\antlr\antlr4\runtime\Go\antlr\parser_atn_simulator.go
     270ms     12.79s (flat, cum) 55.54% of Total
         .          .   1031:   }
         .          .   1032:   p.closureWork(config, configs, closureBusy, collectPredicates, fullCtx, depth, treatEOFAsEpsilon)
         .          .   1033:}
         .          .   1034:
         .          .   1035:// Do the actual work of walking epsilon edges//
      10ms       10ms   1036:func (p *ParserATNSimulator) closureWork(config ATNConfig, configs ATNConfigSet, closureBusy *Set, collectPredicates, fullCtx bool, depth int, treatEOFAsEpsilon bool) {
      20ms       30ms   1037:   state := config.GetState()
         .          .   1038:   // optimization
      40ms      170ms   1039:   if !state.GetEpsilonOnlyTransitions() {
         .      3.88s   1040:           configs.Add(config, p.mergeCache)
         .          .   1041:           // make sure to not return here, because EOF transitions can act as
         .          .   1042:           // both epsilon transitions and non-epsilon transitions.
         .          .   1043:   }
      90ms      350ms   1044:   for i := 0; i < len(state.GetTransitions()); i++ {
      30ms       50ms   1045:           t := state.GetTransitions()[i]
         .          .   1046:           _, ok := t.(*ActionTransition)
         .          .   1047:           continueCollecting := collectPredicates && !ok
         .      1.76s   1048:           c := p.getEpsilonTarget(config, t, continueCollecting, depth == 0, fullCtx, treatEOFAsEpsilon)
      10ms       10ms   1049:           if ci, ok := c.(*BaseATNConfig); ok && ci != nil {
      20ms       60ms   1050:                   if !t.getIsEpsilon() && closureBusy.add(c) != c {
         .          .   1051:                           // avoid infinite recursion for EOF* and EOF+
         .          .   1052:                           continue
         .          .   1053:                   }
         .          .   1054:                   newDepth := depth
         .          .   1055:
         .          .   1056:                   if _, ok := config.GetState().(*RuleStopState); ok {
         .          .   1057:
         .          .   1058:                           // target fell off end of rule mark resulting c as having dipped into outer context
         .          .   1059:                           // We can't get here if incoming config was rule stop and we had context
         .          .   1060:                           // track how far we dip into outer context.  Might
         .          .   1061:                           // come in handy and we avoid evaluating context dependent
         .          .   1062:                           // preds if p is > 0.
         .          .   1063:
         .          .   1064:                           if closureBusy.add(c) != c {
         .          .   1065:                                   // avoid infinite recursion for right-recursive rules
         .          .   1066:                                   continue
         .          .   1067:                           }
         .          .   1068:
         .          .   1069:                           if p.dfa != nil && p.dfa.precedenceDfa {
         .          .   1070:                                   if t.(*EpsilonTransition).outermostPrecedenceReturn == p.dfa.atnStartState.GetRuleIndex() {
         .          .   1071:                                           c.setPrecedenceFilterSuppressed(true)
         .          .   1072:                                   }
         .          .   1073:                           }
         .          .   1074:
         .          .   1075:                           c.SetReachesIntoOuterContext(c.GetReachesIntoOuterContext() + 1)
         .          .   1076:                           configs.SetDipsIntoOuterContext(true) // TODO: can remove? only care when we add to set per middle of p method
         .          .   1077:                           newDepth--
         .          .   1078:                           if ParserATNSimulatorDebug {
         .          .   1079:                                   fmt.Println("dips into outer ctx: " + c.String())
         .          .   1080:                           }
         .          .   1081:                   } else if _, ok := t.(*RuleTransition); ok {
         .          .   1082:                           // latch when newDepth goes negative - once we step out of the entry context we can't return
      10ms       10ms   1083:                           if newDepth >= 0 {
         .          .   1084:                                   newDepth++
         .          .   1085:                           }
         .          .   1086:                   }
      30ms      6.45s   1087:                   p.closureCheckingStopState(c, configs, closureBusy, continueCollecting, fullCtx, newDepth, treatEOFAsEpsilon)
         .          .   1088:           }
         .          .   1089:   }
      10ms       10ms   1090:}
         .          .   1091:
         .          .   1092:func (p *ParserATNSimulator) getRuleName(index int) string {
         .          .   1093:   if p.parser != nil && index >= 0 {
         .          .   1094:           return p.parser.GetRuleNames()[index]
         .          .   1095:   }
```

**Comment by davesisson** [comment] 2017-12-09 03:23
So there are two things to watch out in the hash implementation:

1)  The uint conversion code is there to fix the behavior on arm.
2)  There was an issue with 64-bit rotation.  I believe we need to handle 32-bit and 64-bit ints.

As long as we can make the code work with those two constraints we should be good to change the implementation.  I'm all for more speed!

**Comment by neatnerd** [comment] 2017-12-09 08:48
@davesisson pls, provide more details. link to issue, ideally unit tests to prevent regression

**Comment by davesisson** [comment] 2017-12-10 04:06
Issue #1858 was the arm related issue, issue #2060 talks about the hash issues.

I agree there should be some unit tests to make the library safe.

**Comment by mike-lischke** [comment] 2017-12-19 15:06
@Lacuno Sorry for chiming in here with questions not related to the Go target, but are you serious with the claim that the query:

```
SELECT SUM((IFNULL(X, 0) - IFNULL(Y, 0) - IFNULL(Z, 0) - (IFNULL(XX, 0) - IFNULL(YY, 0) -
IFNULL(ZZ, 0))) * IFNULL(ASDF, 0)) AS `REVENUE` FROM SALES_FLAT
```

will take up to a full second parse time for you? Such a simple thing? I tried it with my MySQL grammar and it parses in 6-9ms in Java and 1ms in C++. Something is terribly wrong with your parser or grammar (or you have a damn slow machine :) )

**Comment by nicolaferraro** [comment] 2018-10-24 10:16
I'm doing a test to parse a 1k chars Java file with Golang target. First execution takes **10 seconds** to create the parser tree. Subsequent ones take 20ms.

It's the Java grammar shipped here as example. There should be something wrong in the parser impl. Does somebody have any hint?
The lexer takes ~0ms to process the full input.

**Comment by tarasbogach** [comment] 2018-12-04 20:41
target: Go, gremmar: https://github.com/antlr/grammars-v4/tree/master/html, input: 120KB HTML file.
35 first lines (1.5KB) tooks 30 seconds. Definitely something wrong with Go target.

**Comment by exander77** [comment] 2020-11-05 16:44
Any news on this?

**Comment by exander77** [comment] 2020-11-13 00:15
> So there are two things to watch out in the hash implementation:
> 
> 1. The uint conversion code is there to fix the behavior on arm.
> 2. There was an issue with 64-bit rotation.  I believe we need to handle 32-bit and 64-bit ints.
> 
> As long as we can make the code work with those two constraints we should be good to change the implementation. I'm all for more speed!

I see these errors on arm:
:2763: constant 4230534781 overflows int
:2787: constant 4230534781 overflows int
:6671: constant 2740715144 overflows int
:6671: constant 4294965233 overflows int
:6836: constant 3011247752 overflows int
:6836: constant 4294965233 overflows int
:11550: constant 4244674173 overflows int
:11975: constant 4292870143 overflows int

**Comment by jjeffcaii** [comment] 2021-08-03 13:54
Now that it is 2021, has this problem been solved?

**Comment by exander77** [comment] 2021-08-03 15:31
@jjeffcaii I doubt that.

**Comment by jjeffcaii** [comment] 2021-08-05 13:51
@exander77 I do some tuning work and fixes some codes, now the performace is acceptable, I think. 🤣 

The SQL `SELECT DATE_FORMAT(IF(COUNT(*)>0,'2021-01-02','2020-01-01'),'%Y') AS cc FROM student WHERE uid BETWEEN 1 AND 5` which used the official mysql grammar v4, it only cost 171ms now. (the original runtime cost 4.7s).

**Comment by kirito41dd** [comment] 2021-09-10 11:42
My case is more extreme... It takes me over 200s to parse 15 lines of code in Golang.... Is it possible to be fixed in the near future? 

antlr/grammars-v4#2327

**Comment by jjeffcaii** [comment] 2021-09-10 12:40
@kirito41dd I did some tuning work, see https://github.com/antlr/antlr4/pull/3243, but the PR hasn't been merged yet.
You can try my fork repo instead, I believe that will be faster. 🚀 

```go.mod
module xxxxxx

go 1.16

require(
	github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210803070921-b358b509191a
)

replace github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20210803070921-b358b509191a => github.com/jjeffcaii/antlr4/runtime/Go/antlr v0.0.0-20210805132115-88c2159aab9e
```

**Comment by kirito41dd** [comment] 2021-09-11 06:21
@jjeffcaii   Thanks,It is effective. For the example in antlr/grammars-v4#2327, it is completed in 0s. For the large files in my project, change from 1000s to 200s.

**Comment by parrt** [comment] 2021-09-24 15:35
Hi. we just merged https://github.com/antlr/antlr4/pull/3243   Can other folks pull that down and see if it improves performance? thanks!

**Comment by kirito41dd** [comment] 2021-09-28 03:47
@parrt Look at my last message, the speed has improved, but it is far from java runtime

**Comment by parrt** [comment] 2021-09-28 22:18
Closed by https://github.com/antlr/antlr4/pull/3243

**Closed by parrt** 2021-09-28 22:18 UTC
Labels: comp:performance
