### ISSUE TITLE
Fragments do not work as expected

### ISSUE THREAD

**Issue by monrealis** [antlr/antlr4#3016] opened 2020-12-27 01:07 UTC
I'm working on a plantuml grammar and fragments do not work as expected:

This works well:
```
relationType
:
	(
		'|o'
		| '||'
		| '}o'
		| '}|'
		| '}'
	)
	(
		(
			'-'+
			(
				'left'
				| 'right'
				| 'top'
				| 'down'
			) '-'+
		)
		| '-'+
	)
	(
		'{'
		| 'o{'
		| 'o|'
		| '|{'
		| '||'
	)
	| '-->'
;
```

This gives `line 34:16 no viable alternative at input '-------down'` :

```
relationType
:
	(
		'|o'
		| '||'
		| '}o'
		| '}|'
		| '}'
	)
	(
		(
			'-'+ DIRECTION '-'+
		)
		| '-'+
	)
	(
		'{'
		| 'o{'
		| 'o|'
		| '|{'
		| '||'
	)
	| '-->'
;

fragment
DIRECTION
:
	'left'
	| 'right'
	| 'top'
	| 'down'
;
```

Line:
`    A7 }o-------down----------{ B7`

**Comment by monrealis** [comment] 2020-12-27 01:11
4.9 gives " implicit definition of token DIRECTION in parser", while 4.4 is silent.

**Comment by monrealis** [comment] 2020-12-27 01:17
This works too:
```
RELATION_TYPE
:
	(
		'|o'
		| '||'
		| '}o'
		| '}|'
		| '}'
	)
	(
		(
			'-'+ (DIRECTION) '-'+
		)
		| '-'+
	)
	(
		'{'
		| 'o{'
		| 'o|'
		| '|{'
		| '||'
	)
	| '-->'
;
```
fragment
DIRECTION
:
	'left'
	| 'right'
	| 'top'
	| 'down'
;

**Comment by monrealis** [comment] 2020-12-27 01:20
![image](https://user-images.githubusercontent.com/2280367/103161955-652c6c80-47f2-11eb-92ae-49cabab903f1.png)

**Comment by KvanTTT** [comment] 2020-12-27 10:32
> 4.9 gives " implicit definition of token DIRECTION in parser", while 4.4 is silent.

That's just correct behavior because you can't use fragment token inside parse rule.

**Comment by monrealis** [comment] 2020-12-27 13:26
I see two minor issues here:
* The behavior changes when you inline fragment inside parser rule. That's not how inlining should work, as understood by most IT people. Is there a reason for that?
* Google says that fragment will never be counted as a token, but the tool says "implicit definition of token DIRECTION in parser"

**Comment by KvanTTT** [comment] 2020-12-28 12:38
> The behavior changes when you inline fragment inside parser rule. That's not how inlining should work, as understood by most IT people. Is there a reason for that?

There is no common understanding of how inline lexer fragments work in IT because grammars are a specific topic. In ANTLR fragment lexer rules don't exist themselves, they are used within other real tokens for lexer simplification.

> Google says that fragment will never be counted as a token, but the tool says "implicit definition of token DIRECTION in parser"

Yes, `DIRECTION` token does not exist that's why it's being created in an implicit way. But I agree, this error is quite confusing and should be renamed to something like `unable to use fragment rule in parser`.

**Comment by KvanTTT** [comment] 2020-12-29 13:48
Also, it's a duplicate of #2886

**Comment by KvanTTT** [comment] 2021-11-07 17:09
@parrt @ericvergnaud please close since it's duplicate.

**Closed** 2021-11-07 17:13 UTC
