### ISSUE TITLE
Incorrect childs generation with array of element label

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4#1163] opened 2016-04-07 13:30 UTC
I have the following rule in grammar:

``` ANTLR
multiply_expression
    : expression (op=('+' | '-') expression)*
    ;
```

But after parser generation I got the following childs in Multiply_expressionContext (C# runtime):

``` CSharp
public partial class Multiply_expressionContext : ParserRuleContext {
    public IToken op;   // Incorrect - should be array of IToken.
    ...
    public ExpressionContext[] expression() {    // Correct - array of Expression.
        return GetRuleContexts<Expression>();
    }
}
```

**Comment by beardlybread** [comment] 2016-04-08 20:07
Is `multiply_expression` defined the same way as `additive_expression` in the grammar?

**Comment by KvanTTT** [comment] 2016-04-08 23:41
Sorry, it's my fault, I replaced additive_expression with multiply_expression.

**Comment by beardlybread** [comment] 2016-04-09 00:45
I fed this to the Java runtime, and I get analogous results:

```antlr
grammar Agrammar;
additiveExpression : expression (op=OP expr=expression)* ;
expression : Number ;
Number : [0-9]+ ;
OP : '+' | '-' ;
```

Looking at the code, though, I think this is the way it's intended to work.  Both symbols (`op` and `expr`) are only referenced inside what appears to be the loop that is giving the behavior of the Kleene star:

```java
	public final AdditiveExpressionContext additiveExpression() throws RecognitionException {
		...
		try {
			enterOuterAlt(_localctx, 1);
			{
			setState(4);
			expression();
			setState(9);
			_errHandler.sync(this);
			_la = _input.LA(1);
			while (_la==OP) {
				{
				{
				setState(5);
				((AdditiveExpressionContext)_localctx).op = match(OP);
				setState(6);
				((AdditiveExpressionContext)_localctx).expr = expression();
				}
				}
				setState(11);
				_errHandler.sync(this);
				_la = _input.LA(1);
			}
			}
		}
```

so in a sense they're kind of behaving like `thing` in

```java
for (Object thing: things) {
...
}
```

I'll play with this some more and see.

**Comment by KvanTTT** [comment] 2016-04-09 07:49
I know about this workaround. But it's yet another rule. And this what I would like to avoid.

**Comment by ericvergnaud** [comment] 2016-04-09 08:12
I believe it is indeed the way it's supposed to work.
If you think about it, OP being a token, it is an invariant from the parser's point of view, so there's no need to distinguish between '+' and '-' since that is what was written in the lexer (the 2 are equivalent).
If you need to distinguish between them, then you might want to try using 2 different tokens, or a grammar rule.
(I haven't tried it, so I might be wrong)

**Comment by KvanTTT** [comment] 2016-04-09 09:21
There are cases in which tokens should be distinguished. In this case I want to use the value of operator in _Visitor_:
```CSharp
for (int i = 1; i < context.expression().Length; i++)
{
    string opValue = context.op(i - 1).GetText();
}
```
Without op label it would be tricky.
Anyway such behaviour should be considered as bug.

**Comment by ericvergnaud** [comment] 2016-04-09 12:57
Have you tried the proposed alternatives?

**Comment by beardlybread** [comment] 2016-04-09 14:21
I did one more thing and tried to assign a label to the star expression directly:

```antlr
grammar Agrammar;

additiveExpression : expression star=(opExpression)* ;
opExpression : op=OP expr=expression ;
expression : Number ;
Number : [0-9]+ ;
OP : '+' | '-' ;
```

which gives the error `label star assigned to a block which is not a set`.  This seems to imply that `SetAST` and `BlockAST` would need to be semantically identical from the perspective of code generation.  Even if we grant that this should be considered a bug, it looks like it would require the code to fundamentally change, so I doubt it will happen.  Maybe it could be considered as a major feature addition?

**Comment by ericvergnaud** [comment] 2016-04-09 15:32
In the above grammar, if you visit opExpression you'll find that op contains the actual token text, so there is neither a bug or a need for a feature

**Comment by beardlybread** [comment] 2016-04-09 17:19
@ericvergnaud Just to clarify, I was speaking hypothetically.  I wasn't actually suggesting a fundamental restructuring of the Antlr AST classes would be a good "feature" to add. :smile:

**Comment by parrt** [comment] 2016-12-10 22:15
intended behavior. `+=` or repeated references (not parses) give arrays.

**Closed by parrt** 2016-12-10 22:15 UTC
