### ISSUE TITLE
Tool path handling on Windows

### ISSUE THREAD

**Issue by egonelbre** [antlr/antlr4#1087] opened 2015-12-27 16:38 UTC
`antlr-4.5.1-complete.jar` doesn't behave consistently with "/" and "\" on Windows.

Initial folder structure:

```
|   antlr-4.5.1-complete.jar
\---src
    \---main
        \---antlr
                example.g4
```

Case 1. After `java -jar antlr-4.5.1-complete.jar -o src\main\generated src\main\antlr\example.g4`:

```
|   antlr-4.5.1-complete.jar
\---src
    \---main
        +---antlr
        |       example.g4
        \---generated
            \---src
                \---main
                    \---antlr
                            example.tokens
                            exampleBaseListener.java
                            exampleLexer.java
                            exampleLexer.tokens
                            exampleListener.java
                            exampleParser.java
```

Case 2. After `java -jar antlr-4.5.1-complete.jar -o src/main/generated src/main/antlr/example.g4`:

```
|   antlr-4.5.1-complete.jar
\---src
    \---main
        +---antlr
        |       example.g4
        \---generated
                example.tokens
                exampleBaseListener.java
                exampleLexer.java
                exampleLexer.tokens
                exampleListener.java
                exampleParser.java
```

According to #683 the Case 1. behavior is correct, however in cross-platform scripts you are quite likely to use the path in Case 2.

Ideally both would behave exactly the same way.

**Comment by mike-lischke** [comment] 2017-04-19 08:02
Also this one is likely a duplicate of #638.

**Closed** 2017-11-05 16:49 UTC
Labels: type:improvement
