### ISSUE TITLE
Cannot mix left recursive rules with rule arguments

### ISSUE THREAD

**Issue by martint** [antlr/antlr4#781] opened 2014-12-31 06:03 UTC
The following grammar fails to compile with the error below:

```
grammar Test;

a
    : b c[$b.ctx]
    | a b
    ;

b: 'x';
c[ParserRuleContext context]: 'y';
```

```
error(50): :2:45: syntax error: '$' came as a complete surprise to me while looking for rule element

org\antlr\v4\parse\GrammarTreeVisitor.g: node from after line 2:26 mismatched tree node: <unexpected: [@21,47:47='$',<18>,2:45], resync=c<tokenIndex=11>> expecting <UP>
org\antlr\v4\parse\GrammarTreeVisitor.g: node from line 6:9 mismatched tree node: * expecting <UP>
org\antlr\v4\parse\GrammarTreeVisitor.g: node from after line 2:26 mismatched tree node: <unexpected: [@21,47:47='$',<18>,2:45], resync=c<tokenIndex=11>> expecting <UP>
org\antlr\v4\parse\GrammarTreeVisitor.g: node from line 6:9 mismatched tree node: * expecting <UP>
org\antlr\v4\parse\GrammarTreeVisitor.g: node from after line 2:26 mismatched tree node: <unexpected: [@21,47:47='$',<18>,2:45], resync=c<tokenIndex=11>> expecting <UP>
org\antlr\v4\parse\GrammarTreeVisitor.g: node from line 6:9 mismatched tree node: * expecting <UP>
```

It works if I factor out `b c[$b.ctx]` into a separate rule or if I remove the left recursion from `a`:

```
grammar Test;

a : d | a b;
b: 'x';
c[ParserRuleContext context]: 'y';
d: b c[$b.ctx];
```

**Comment by sharwell** [comment] 2015-01-01 00:29
This is a duplicate of #775

**Closed by sharwell** 2015-01-01 00:29 UTC
