### ISSUE TITLE
C++ runtime build failed due to utfcpp test failed.

### ISSUE THREAD

**Issue by g199209** [antlr/antlr4#2990] opened 2020-12-04 06:43 UTC
@Clcanny 

#2892 adds `utfcpp` dependancy, but this library can not be built & tested as expect.

```
$make
[  2%] Skipping update step for 'utfcpp'
[  2%] Performing configure step for 'utfcpp'
-- Configuring done
-- Generating done
-- Build files have been written to: ...................
[  2%] Performing build step for 'utfcpp'
[  9%] Built target docsample
[ 18%] Built target gtest
[ 27%] Built target gmock
[ 36%] Built target gmock_main
[ 45%] Built target gtest_main
[ 54%] Built target negative
[ 77%] Built target apitests
[ 90%] Built target noexceptionstests
[100%] Built target cpp11
[  2%] Performing install step for 'utfcpp'
[  9%] Built target docsample
[ 18%] Built target gtest
[ 27%] Built target gmock
[ 36%] Built target gmock_main
[ 45%] Built target gtest_main
[ 54%] Built target negative
[ 77%] Built target apitests
[ 90%] Built target noexceptionstests
[100%] Built target cpp11
Install the project...
-- Install configuration: ""
-- ...................
[  2%] Performing test step for 'utfcpp'
Running tests...
Test project ........
    Start 1: negative_test
1/4 Test #1: negative_test ....................***Failed    0.00 sec
    Start 2: cpp11_test
2/4 Test #2: cpp11_test .......................***Failed    0.00 sec
    Start 3: api_test
3/4 Test #3: api_test .........................***Failed    0.00 sec
    Start 4: noexceptions_test
4/4 Test #4: noexceptions_test ................***Failed    0.00 sec

0% tests passed, 4 tests failed out of 4

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - negative_test (Failed)
	  2 - cpp11_test (Failed)
	  3 - api_test (Failed)
	  4 - noexceptions_test (Failed)
Errors while running CTest
make[3]: *** [test] Error 8
make[2]: *** [runtime/utfcpp-prefix/src/utfcpp-stamp/utfcpp-test] Error 2
make[1]: *** [runtime/CMakeFiles/utfcpp.dir/all] Error 2
make: *** [all] Error 2
```

`cmake` version: 3.16.2
`gcc` & `g++` version: 9.3.0

**Comment by Clcanny** [comment] 2020-12-04 09:21
Can you provide os version? I will test it on my machine.

**Comment by g199209** [comment] 2020-12-04 09:25
> Can you provide os version? I will test it on my machine.

OS version: CentOS 7
Kernel vesion: 4.1.0

**Comment by Clcanny** [comment] 2020-12-04 09:32
I have tested it on my machine, it is okay:

```bash
[  3%] Performing install step for 'utfcpp'
[  9%] Built target docsample
[ 18%] Built target gtest
[ 27%] Built target negative
[ 36%] Built target gtest_main
[ 45%] Built target gmock
[ 54%] Built target cpp11
[ 63%] Built target gmock_main
[ 77%] Built target noexceptionstests
[100%] Built target apitests
Install the project...
-- Install configuration: ""
-- Installing: /home/demons/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/install/include/utf8cpp
-- Installing: /home/demons/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/install/include/utf8cpp/utf8.h
// ...
[  3%] Performing test step for 'utfcpp'
Running tests...
Test project /home/demons/antlr4/runtime/Cpp/build/runtime/utfcpp-prefix/src/utfcpp-build
    Start 1: negative_test
1/4 Test #1: negative_test ....................   Passed    0.00 sec
    Start 2: cpp11_test
2/4 Test #2: cpp11_test .......................   Passed    0.00 sec
    Start 3: api_test
3/4 Test #3: api_test .........................   Passed    0.00 sec
    Start 4: noexceptions_test
4/4 Test #4: noexceptions_test ................   Passed    0.00 sec

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   0.01 sec
[  3%] Completed 'utfcpp'
[  3%] Built target utfcpp
```

```bash
# uname -a
Linux iZ6we32xzabtc8wc695l9wZ 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64 GNU/Linux
# gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOS
# cmake --version
cmake version 3.7.2
```

However, I will test it on Centos, please wait.

**Comment by Clcanny** [comment] 2020-12-04 11:24
GCC and CMake are too old in Centos 7, so I use Centos 8.

```dockerfile
FROM centos:8
RUN yum -y install git cmake make gcc gcc-c++ libuuid-devel
RUN git clone https://github.com/antlr/antlr4.git
WORKDIR antlr4/runtime/Cpp
RUN sed -i 's/# set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_UTF8_INSTEAD_OF_CODECVT")/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DUSE_UTF8_INSTEAD_OF_CODECVT")/g' CMakeLists.txt
RUN mkdir build
WORKDIR build
RUN cmake .. && make -j8 && make install -j8
RUN cat /etc/os-release
RUN cmake --version
RUN make --version
RUN gcc --version
```

```bash
Step 9/12 : RUN cat /etc/os-release
 ---> Running in 9695339d0144
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

Removing intermediate container 9695339d0144
 ---> 24fba590ed07
Step 10/12 : RUN cmake --version
 ---> Running in 3a59746b03f4
cmake version 3.11.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Removing intermediate container 3a59746b03f4
 ---> 6f3382d4888d
Step 11/12 : RUN make --version
 ---> Running in 31a722d36973
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Removing intermediate container 31a722d36973
 ---> daabd327954a
Step 12/12 : RUN gcc --version
 ---> Running in aff3128a692e
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Removing intermediate container aff3128a692e
 ---> 2b04299317d7
Successfully built 2b04299317d7
Successfully tagged build-antlr4-in-centos-8:latest
```

I can't reproduce the problem by myself. Please provide more informations to help me:

1. Enter antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp and execute `mkdir build && cmake .. && make && make test`. Check if utfcpp has problem.
2. Execute `./tests/apitests` and `./tests/noexceptionstests` to check which tests break.

Thanks a lot for your issue!

**Comment by g199209** [comment] 2020-12-04 11:43
```
[19:39:15:192-168-152-33@~/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build]
$cmake ..
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/local/bin/c++
-- Check for working CXX compiler: /usr/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.5")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mingfei.gao/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build
[19:39:20:192-168-152-33@~/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build]
$make
Scanning dependencies of target docsample
[  4%] Building CXX object CMakeFiles/docsample.dir/samples/docsample.cpp.o
[  9%] Linking CXX executable docsample
[  9%] Built target docsample
Scanning dependencies of target gtest
[ 13%] Building CXX object extern/gtest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[ 18%] Linking CXX static library libgtest.a
[ 18%] Built target gtest
Scanning dependencies of target gmock
[ 22%] Building CXX object extern/gtest/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 27%] Linking CXX static library libgmock.a
[ 27%] Built target gmock
Scanning dependencies of target gmock_main
[ 31%] Building CXX object extern/gtest/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 36%] Linking CXX static library libgmock_main.a
[ 36%] Built target gmock_main
Scanning dependencies of target gtest_main
[ 40%] Building CXX object extern/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 45%] Linking CXX static library libgtest_main.a
[ 45%] Built target gtest_main
Scanning dependencies of target negative
[ 50%] Building CXX object tests/CMakeFiles/negative.dir/negative.cpp.o
[ 54%] Linking CXX executable negative
[ 54%] Built target negative
Scanning dependencies of target apitests
[ 59%] Building CXX object tests/CMakeFiles/apitests.dir/test_checked_api.cpp.o
[ 63%] Building CXX object tests/CMakeFiles/apitests.dir/test_unchecked_api.cpp.o
[ 68%] Building CXX object tests/CMakeFiles/apitests.dir/test_checked_iterator.cpp.o
[ 72%] Building CXX object tests/CMakeFiles/apitests.dir/test_unchecked_iterator.cpp.o
[ 77%] Linking CXX executable apitests
[ 77%] Built target apitests
Scanning dependencies of target noexceptionstests
[ 81%] Building CXX object tests/CMakeFiles/noexceptionstests.dir/test_unchecked_api.cpp.o
[ 86%] Building CXX object tests/CMakeFiles/noexceptionstests.dir/test_unchecked_iterator.cpp.o
[ 90%] Linking CXX executable noexceptionstests
[ 90%] Built target noexceptionstests
Scanning dependencies of target cpp11
[ 95%] Building CXX object tests/CMakeFiles/cpp11.dir/test_cpp11.cpp.o
[100%] Linking CXX executable cpp11
[100%] Built target cpp11
[19:39:43:192-168-152-33@~/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build]
$make test
Running tests...
Test project /home/mingfei.gao/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build
    Start 1: negative_test
1/4 Test #1: negative_test ....................***Failed    0.00 sec
    Start 2: cpp11_test
2/4 Test #2: cpp11_test .......................***Failed    0.00 sec
    Start 3: api_test
3/4 Test #3: api_test .........................***Failed    0.00 sec
    Start 4: noexceptions_test
4/4 Test #4: noexceptions_test ................***Failed    0.00 sec

0% tests passed, 4 tests failed out of 4

Total Test time (real) =   0.01 sec

The following tests FAILED:
	  1 - negative_test (Failed)
	  2 - cpp11_test (Failed)
	  3 - api_test (Failed)
	  4 - noexceptions_test (Failed)
Errors while running CTest
make: *** [test] Error 8
```

I am not familiar with CTest, how can I found why the test failed?

**Comment by Clcanny** [comment] 2020-12-04 11:46
> I am not familiar with CTest, how can I found why the test failed?

You can run `./tests/apitests` directly in /home/mingfei.gao/Opensource/antlr4/runtime/Cpp/build/runtime/thirdparty/utfcpp/build directly to see why it failed.

**Comment by g199209** [comment] 2020-12-07 02:33
I have found why the test failed. I have installed a newer version GCC in CentOS 7, so there exist two `libstdc++.so.6`.  `apitest` depends on newer version `libstdc++.so.6`:

```
$ldd apitests
./apitests: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./apitests)
./apitests: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./apitests)
./apitests: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./apitests)
./apitests: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./apitests)
	linux-vdso.so.1 =>  (0x00007ffc72917000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007ff2bf8bc000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff2bf5ba000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff2bf3a4000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff2bf188000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff2bedc5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff2bfbc4000)
```

The correct `libstdc++.so.6` is at `/usr/local/lib64`, not at `/lib64`.

So I set the library search path by seting `LD_LIBRARY_PATH` varibale:

```
export LD_LIBRARY_PATH=/usr/local/lib64
```

That solves the problem.

@Clcanny Thanks for your help!

**Comment by Clcanny** [comment] 2020-12-07 03:00
> That solves the problem.

Then I close this issue. Open if you need. Thank you!

**Comment by Clcanny** [comment] 2020-12-07 03:00
> That solves the problem.

I will close this issue. Reopen if you need. Thanks!

**Closed** 2020-12-07 05:21 UTC
