### ISSUE TITLE
[Go] Lexer misidentifies tokens depending on order it encounters them

### ISSUE THREAD

**Issue by Chuckbert** [antlr/antlr4#2060] opened 2017-10-19 16:37 UTC
I am trying to create a Go parser for our dialect of SQL. I have defined keyword tokens in form:
```
KW_ABC : A B C ;

fragment A : [Aa] ;
fragment B : [Bb] ;
fragment C : [Cc] ;
```

There is a NAME token following all the keyword definitions that I've reduced for this issue to a letter or one of a few special characters followed by zero or more letters, special characters and numeric characters. 

When I generate the lexer with the language set to Go, some of the keywords are sometimes misidentified as NAME tokens. In my reduced lexer, if I tokenize the string "ASIN CTCONTROL", the ASIN token is a KW_ASIN token and the CTCONTROL token is a NAME token. If I reverse the tokens, "CTCONTROL ASIN", the first token becomes KW_CTCONTROL and the second one becomes a NAME token.

If I generate the lexer with language Java, the resulting lexer identifies all the keywords correctly.

Not knowing the architecture of the Go lexer runtime, I have had no luck trying to debug the generated Go lexer. Any help understanding what I did wrong or how I can work around any bugs or getting a bug fix would be great.

The smallest lexer I can come up with that illustrates the problem is:
```
// Define a grammar called OddLexer
lexer grammar OddLexer;

options {language = Go;}


KW_ABORTSESSION: A B O R T S E S S I O N  ;
KW_ADD_MONTHS: A D D '_' M O N T H S  ;
KW_ASIN: A S I N  ;
KW_AT: A T  ;
KW_BETWEEN: B E T W E E N  ;
KW_CASE: C A S E  ;
KW_CASE_N: C A S E '_' N  ;
KW_CAST: C A S T  ;
KW_CLASS: C L A S S  ;
KW_COLLATION: C O L L A T I O N  ;
KW_CONNECT: C O N N E C T  ;
KW_CONSTRUCTOR: C O N S T R U C T O R  ;
KW_CONSUME: C O N S U M E  ;
KW_CONTAINS: C O N T A I N S  ;
KW_CONTINUE: C O N T I N U E  ;
KW_CREATE: C R E A T E  ;
KW_CTCONTROL: C T C O N T R O L  ;
KW_DATABASE: D A T A B A S E  ;
KW_DETERMINISTIC: D E T E R M I N I S T I C  ;
KW_ET: E T  ;
KW_FASTEXPORT: F A S T E X P O R T  ;
KW_FETCH: F E T C H  ;
KW_GET: G E T  ;
KW_GROUPING: G R O U P I N G  ;
KW_HASH: H A S H  ;
KW_HASHAMP: H A S H A M P  ;
KW_HASHBAKAMP: H A S H B A K A M P  ;
KW_HASHBUCKET: H A S H B U C K E T  ;
KW_HASHROW: H A S H R O W  ;
KW_HAVING: H A V I N G  ;
KW_IMMEDIATE: I M M E D I A T E  ;
KW_IN: I N  ;
KW_INITIATE: I N I T I A T E  ;
KW_INNER: I N N E R  ;
KW_INOUT: I N O U T  ;
KW_INPUT: I N P U T  ;
KW_INSTANCE: I N S T A N C E  ;
KW_INTEGERDATE: I N T E G E R D A T E  ;
KW_INTERSECT: I N T E R S E C T  ;
KW_INTERVAL: I N T E R V A L  ;
KW_INTO: I N T O  ;
KW_ITERATE: I T E R A T E  ;
KW_JOIN: J O I N  ;
KW_LEADING: L E A D I N G  ;
KW_LOADING: L O A D I N G  ;
KW_LOCATOR: L O C A T O R  ;
KW_LOGGING: L O G G I N G  ;

NAME :
    ( LETTER | SPECIAL_CHAR )
    ( LETTER | SPECIAL_CHAR | DIGIT )*
    ;

fragment
LETTER :
    [a-zA-Z]
    ;

fragment
DIGIT :
    [0-9]
    ;

fragment
SPECIAL_CHAR :
    '$' | '#' | '_'
    ;


fragment A: [aA];
fragment B: [bB];
fragment C: [cC];
fragment D: [dD];
fragment E: [eE];
fragment F: [fF];
fragment G: [gG];
fragment H: [hH];
fragment I: [iI];
fragment J: [jJ];
fragment K: [kK];
fragment L: [lL];
fragment M: [mM];
fragment N: [nN];
fragment O: [oO];
fragment P: [pP];
fragment Q: [qQ];
fragment R: [rR];
fragment S: [sS];
fragment T: [tT];
fragment U: [uU];
fragment V: [vV];
fragment W: [wW];
fragment X: [xX];
fragment Y: [yY];
fragment Z: [zZ];

SINGLE_LINE_COMMENT : '--' ~[\r\n]* -> channel(HIDDEN) ;
WS : [ \f\t\r\n] -> channel(HIDDEN) ;

MULTILINE_COMMENT
 : '/*' .*? ( '*/' | EOF ) -> channel(HIDDEN)
 ;

UNEXPECTED_CHAR  : . ; // everything else
```

I use the following test to show the problem (the tests have to be run individually...if they are run together, the same word is misidentified as a NAME for both tests):
```
package parser

import (
	"testing"

	"github.com/antlr/antlr4/runtime/Go/antlr"
)

func Test1(t *testing.T) {
	words := "ASIN CTCONTROL"
	findNames(t, words)
}

func Test2(t *testing.T) {
	words := "CTCONTROL ASIN"
	findNames(t, words)
}

func findNames(t *testing.T, words string) {
	input := antlr.NewInputStream(words)
	lexer := NewOddLexer(input)
	stream := antlr.NewCommonTokenStream(lexer, 0)
	for i := 1; ; i++ {
		tok := stream.LT(i)
		if tok.GetTokenType() == antlr.TokenEOF {
			break
		}
		if lexer.GetSymbolicNames()[tok.GetTokenType()] == "NAME" {
			t.Errorf("Keyword %s misidentified as a NAME", tok.GetText())
		}
	}
}
```

If I remove either of the SINGLE_LINE_COMMENT or MULTILINE_COMMENT or try to simplify the NAME token's definition, this sample doesn't seem to illustrate the problem.

I am using antlr-4.7.complete.jar and the latest runtime.

**Comment by bramp** [comment] 2017-10-21 22:17
This may be related to my observations in #2040 where repeated runs of the lexer could produce different output.

**Comment by Chuckbert** [comment] 2017-11-15 00:16
It appears to me that the problem is occurring in func (l *LexerATNSimulator) addDFAState(configs ATNConfigSet) in lexer_atn_simulator.go. It appears that the line `hash := proposed.hash()` results in the same hash value for different DFAStates that contain different configs.

I printed out the hash value and proposed value and got duplicate hash values for proposed values that print out as the following two values:
* %!d(string=[(569,3,[190 $]), (547,48,[543 $]), (551,48,[543 $]), (549,48,[543 $]), (96,48,[$])]):=>48%!s(MISSING)
* %!d(string=[(581,17,[297 $]), (547,48,[543 $]), (551,48,[543 $]), (549,48,[543 $]), (96,48,[$])]):=>48%!s(MISSING)

The hash value for these two proposed values is 67567852119500843.

Since the state.stateNumber (what I believe is the 569 and 581 in the string values shown above) is used in calculating the hash value, it looks to me like there is a problem in the calculation of the hash value.

If someone could confirm this and offer a corrected hash algorithm, it would get me on my way much quicker.

I removed the check to see if there is an existing DFAState for the configs and the lexer behaved much better when it didn't get tripped up by the collision.

**Comment by bramp** [comment] 2017-11-15 07:23
(I'm not a antlr dev but) That hash code does look suspicious, but even if it was better there would always be a chance of a hash collision. Since this is stored in a map keyed by the hash, I suspect this would do the wrong thing in that case, unlike the Java implementation which uses a HashSet keyed by the DFAState.

However, I started to try and reproduce your issue, and based on your grammar, and test, with the latest Antlr it works fine for me, and I do not observe the behaviour you are seeing.

**Comment by Chuckbert** [comment] 2017-11-15 17:41
I seem to have tracked down the problem. `murmurUpdate` in dfa_state.go has two lines that do bit shifts and have comments indicating that the operation is doing a rotl32. This is true if the int values that are being rotated are 32 bits. When int is a 64 bit value, things are not rotated correctly and lots of bits get set on that shouldn't be.

I changed the line:
* `k1 = (k1 << 15) | (k1 >> 17) // rotl32(k1, 15)`

to:
* `k1 = int(bits.RotateLeft(uint(k1), 15))`

And:
* `h1 = (h1 << 13) | (h1 >> 19) // rotl32(h1, 13)`

to:
* `h1 = int(bits.RotateLeft(uint(h1), 13))`

The lexer behaves much better with the bit rotation actually rotating the values.

**Comment by davesisson** [comment] 2017-12-06 17:56
@parrt This fix needs to be in the next release.  We encountered the same issue and this fix solved the problem for us.  (The only question is whether we need to come up with an alternate implementation since requiring Go 1.9 may not be something we want to do.)

**Comment by parrt** [comment] 2017-12-06 17:57
Ok, Can you create a PR or have you done so already? I will go through the PRs shortly.

**Comment by davesisson** [comment] 2017-12-06 19:09
Sent out #2149 (I ended up replicating the code from math/bits).

**Comment by jimidle** [comment] 2022-08-22 05:27
I suspect that this issue is now fixed in the dev branch, but i will test using the grammar above.

**Comment by jimidle** [comment] 2022-09-12 06:59
@parrt I have tested using the code above and both tests pass as expected. Previous fixes to hashing and collections as well as conflictingalt have fixed this and probably lots of other things. We can close the PR @2149 without merge as well as this issue.

@Chuckbert - please retest :)

**Comment by parrt** [comment] 2022-09-16 00:04
> 2149?

@jimidle not sure which PR that is. Looks to be an old one.

**Closed by parrt** 2022-09-16 00:04 UTC
Labels: lexers, target:go

**Comment by jimidle** [comment] 2022-09-19 04:21
Yeah - unrelated to my fixes I think. And it was merged a long time ago.

**Comment by parrt** [comment] 2022-09-20 17:16
Ok, what do you mean by closing PR @2149 ?

**Comment by jimidle** [comment] 2022-09-21 04:52
> 

I am no longer sure. I think that I missed that that had already been merged and assumed that it was meant to be a fix for this. So, that comment can be disregarded.
