### ISSUE TITLE
Parameters Initialisation

### ISSUE THREAD

**Issue by heavenkhn** [antlr/antlr4#783] opened 2015-01-04 08:05 UTC
sequence[int n]
locals[int i = 1;] //le i ne s'initialise pas correctement avec 1 il prend toutjours 0
	: 
	(
		{$i<=$n}? INT {System.out.println($i); $i++;}
	)*
	;

I think that all person who reads the book (ANTLR4) have seen this code. 
I tried it but he doesn't initialise the i to 1 but it takes 0 and increment it. 
I printed out to confirm and the result is :

0
1
2

Where n = 2; 

So it take the 0

And to fix it very simple 

sequence[int n]
locals[int i = 1;] //le i ne s'initialise pas correctement avec 1 il prend toutjours 0
	: 
	(
		{$i+1<=$n}? INT {System.out.println($i); $i++;}
	)*
	;

But i would know if it's a bug or a kind of configuration. Thx

**Comment by jimidle** [comment] 2015-01-04 11:33
Please see prior emails to the list. This was a bug introduced in 4.3 which I believe Sam or Ter fixed in 4.4, or at least the latest development tree. 

Jim

**Comment by heavenkhn** [comment] 2015-01-04 15:03
Thx, but i sue the last version 4.4. 
There is another version ??!

**Comment by ericvergnaud** [comment] 2015-01-04 15:11
looks like this was fixed with #672 <https://github.com/antlr/antlr4/issues/672>, after the 4.4 release
a new release is expected soon

Eric

**Comment by heavenkhn** [comment] 2015-01-04 15:14
Nice, thx.

**Comment by sharwell** [comment] 2015-01-04 17:00
Duplicate of #672

**Closed by sharwell** 2015-01-04 17:00 UTC
