### ISSUE TITLE
Grammar Name Conflict Golang with SPARQL issue

### ISSUE THREAD

**Issue by saucesaft** [antlr/antlr4#3758] opened 2022-06-21 22:49 UTC
Hi! So im trying to build a simple sparql parser for golang. Got the grammar for it from here: https://github.com/antlr/grammars-v4/tree/master/sparql

Then i ran this command to generate the code:
`
java -jar antlr-4.10.1-complete.jar -Dlanguage=Go -o parser Sparql.g4`

Now, after i included it into a Go program, without even using it, it errors out with this:
```# dkg-client-go/parser
parser/sparql_parser.go:9806:9: cannot use s (variable of type *RdfLiteralContext) as type antlr.RuleContext in return statement:
	*RdfLiteralContext does not implement antlr.RuleContext (wrong type for String method)
		have String() IStringContext
		want String([]string, antlr.RuleContext) string
parser/sparql_parser.go:9829:13: cannot use NewRdfLiteralContext(p, p.GetParserRuleContext(), p.GetState()) (value of type *RdfLiteralContext) as type IRdfLiteralContext in assignment:
	*RdfLiteralContext does not implement IRdfLiteralContext (wrong type for String method)
		have String() IStringContext
		want String([]string, antlr.RuleContext) string
```

From what i've seen in another issue, i think this might be related to some grammar name conflicts with the code generation, but i dont know how to fix it. If someone recognizes the problem, i'll be glad to make the changes myself and open a pull request. 

Thanks :)

**Comment by kaby76** [comment] 2022-06-23 02:15
Correct. This is the result of a "symbol conflict".

After looking over the generated files, and finding nothing obvious, I decided to check for the problem using automated means. I created a script (see below) that creates a new grammar with  all parser rule symbols with a trailing underscore. It renames a symbol back to the original name without the underscore, and test how it builds.

The problem is "string". A workaround is to rename it to something else, like "string_". This needs to be added to the escaping code in the Antlr tool for Go. @KvanTTT 

```
#!/bin/sh

names=`trparse Sparql.g4 | trxgrep ' //parserRuleSpec/RULE_REF/text()' | sort -u | dos2unix | grep -v -E -e '_$' | grep -v -E -e '^query$'`
newnames=""
for i in $names
do
	newnames="$newnames"$i,$i"_;"
done
newnames="${newnames::-1}"
trparse Sparql.g4 | trrename -r "$newnames" | trsponge -c
for i in $names
do
	fixed=$i'_'
	echo Testing $fixed '=>' $i
	rm -rf testit
	mkdir testit
	pushd testit > /dev/null 2>&1
	cp ../Sparql.g4 .
	trparse Sparql.g4 | trrename -r "$fixed,$i" | trsponge -c > /dev/null 2>&1
	cp -r ../examples .
	cp ../pom.xml .
	trgen -t Go > /dev/null 2>&1
	cd Generated
	make > /dev/null 2>&1
	if [[ "$?" != "0" ]]
	then
		echo "==========================="
		echo $i did not work.
	fi
	cd ..
	rm -rf Generated
	popd > /dev/null 2>&1
	rm -rf testit
done
```

**Comment by jimidle** [comment] 2022-08-22 03:48
This issue can now be closed.

**Comment by kaby76** [comment] 2022-08-22 11:06
Checking into this now...

**Comment by kaby76** [comment] 2022-08-22 11:54
No, it doesn't seem fixed. But, maybe I'm not building the right version of https://github.com/antlr/antlr4/tree/dev.

First, I took the "dev" branch and built the tool complete.jar. Then, I created a Go workspace with that antlr4/runtime/Go/antlr/ directory, and adjusted my makefiles in my trgen-generated driver to make sure the "dev" complete.jar file is used. The build output is:
```
export GO111MODULE=on; go get github.com/antlr/antlr4/runtime/Go/antlr@4.10
java -jar C:/Users/Kenne/Documents/GitHub/antlr4-upstream-dev/tool/target/antlr4-4.10.2-SNAPSHOT-complete.jar -encoding utf-8 -Dlanguage=Go -o parser -lib parser -package parser  parser/Sparql.g4
export GO111MODULE=on; go build Test.go
# example.com/myparser/parser
parser\sparql_parser.go:9805:9: cannot use s (variable of type *RdfLiteralContext) as type antlr.RuleContext in return statement:
        *RdfLiteralContext does not implement antlr.RuleContext (wrong type for String method)
                have String() IStringContext
                want String([]string, antlr.RuleContext) string
parser\sparql_parser.go:9828:13: cannot use NewRdfLiteralContext(p, p.GetParserRuleContext(), p.GetState()) (value of type *RdfLiteralContext) as type IRdfLiteralContext in assignment:
        *RdfLiteralContext does not implement IRdfLiteralContext (wrong type for String method)
                have String() IStringContext
                want String([]string, antlr.RuleContext) string
mingw32-make: *** [makefile:16: program] Error 2
```
Note, I had to do a "go get golang.org/x/exp/slices" ni antlr/ because there is a dependency on the "slices" module.

I made sure to use the "right" grammar in testing, the previous commit: https://github.com/antlr/grammars-v4/tree/72305302b8b82ec35a72593e2fd0c13a841cb602/sparql

I had to fix the grammar to work around this problem.

**Comment by jimidle** [comment] 2022-08-22 12:25
You have to wait for the PR to come in to dev

**Comment by kaby76** [comment] 2022-08-22 13:00
@jimidle Yes, your fix works (`git clone https://github.com/jimidle/antlr4.git; cd antlr4; git checkout feature/3758; ...`, but with the caveat that I need to "cd antlr4/runtime/Go/antlr4; go get golang.org/x/exp/slices").

**Comment by jimidle** [comment] 2022-08-22 13:23
Cool. Thanks for the verify.

**Comment by jimidle** [comment] 2022-08-23 02:31
go.mod is updated and go.sum is added to the repo. We can close this when the PR is merged. 

@parrt There are I think 3 outstanding PRs to fix go runtime bugs. I could merge them but do not have permissions (which also means I cannot get a free Github copilot license ;)

**Comment by parrt** [comment] 2022-08-23 04:30
Merged. Closing.

**Closed by parrt** 2022-08-23 04:30 UTC
